<style>
    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 300;
        src: url(https://static.contineljs.com/fonts/Roboto-Light.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Light.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 400;
        src: url(https://static.contineljs.com/fonts/Roboto-Regular.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Regular.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 500;
        src: url(https://static.contineljs.com/fonts/Roboto-Medium.woff2?v=2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Medium.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 700;
        src: url(https://static.contineljs.com/fonts/Roboto-Bold.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Bold.woff) format("woff");
    }

    * {
        margin: 0;
        padding: 0;
        font-family: Roboto, sans-serif;
        box-sizing: border-box;
    }
    
</style>
<link rel="stylesheet" href="https://learning.oreilly.com/files/public/epub-reader/override_v1.css" crossorigin="anonymous"><link rel="stylesheet" href="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781492092506/files/epub.css" crossorigin="anonymous">
<div style="width: 100%; display: flex; justify-content: center; background-color: black; color: wheat;">
    <section data-testid="contentViewer" class="contentViewer--KzjY1"><div class="annotatable--okKet"><div id="book-content"><div class="readerContainer--bZ89H white--bfCci" style="font-size: 1em; max-width: 70ch;"><div id="sbo-rt-content"><section data-type="chapter" epub:type="chapter" data-pdf-bookmark="Chapter 10. Errors and Testing"><div class="chapter" id="ch10">
        <h1><span class="label">Chapter 10. </span>Errors and Testing</h1>
        
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" id="ix_errors_ch10"></a>To write code is to write errors. Often, an error can be anticipated. Risky activities include actions that interact with outside resources (like files, databases, or web server APIs). Information that comes from outside your code—whether you’re reading it from a web page form or receiving it from another library—may arrive with errors, or in a different form than you expect. But to modify a well-worn cliché, it’s not so much the error as what you do with it that matters.</p>
        
        <p>What should we do with our errors, then? JavaScript’s default behavior is to die at the point of the error, quietly logging a stack trace to the console. However, better options are available. You can capture an error, react to it, modify it, rethrow it, and even hide it if you choose. Compared to many other languages, JavaScript’s error-handling features are relatively underdeveloped. But basic error handling is still just as important, and many of the recipes in this chapter focus on that task.</p>
        
        <p>Defending against errors is essential practice, but it’s equally important to <em>prevent</em> them wherever possible. To that end, there are many testing frameworks that work with JavaScript, including Jest, Mocha, Jasmine, and Karma. With their help, you can write unit tests that guarantee your code is executing as expected. You’ll take a quick look at Jest in this chapter.</p>
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Catching and Neutralizing an Error"><div class="sect1" id="catching_errors">
        <h1>Catching and Neutralizing an Error</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475152647960">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="catching and neutralizing" id="ix_error_neutralizing"></a>You are performing a task that may not succeed, and you don’t want an error to interrupt your code or appear in the developer console.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475152645000">
        <h2>Solution</h2>
        
        <p>Wrap the section of your code in a <code>try...catch</code> block, like this one:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="k">try</code> <code class="p">{</code>
          <code class="c1">// This is guaranteed to fail with a URIError</code>
          <code class="kr">const</code> <code class="nx">uri</code> <code class="o">=</code> <code class="nb">decodeURI</code><code class="p">(</code><code class="s1">'http%test'</code><code class="p">);</code>
        
          <code class="c1">// We never get here</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'Success!'</code><code class="p">);</code>
        <code class="p">}</code>
        <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">error</code><code class="p">);</code>
        <code class="p">}</code></pre>
        
        <p><a data-type="indexterm" data-primary="properties" data-secondary="Error object" id="idm45475152641672"></a>When the <code>decodeURI()</code> function fails and an error occurs, execution jumps to the <code>catch</code> block. <a data-type="indexterm" data-primary="exception, Error object" id="idm45475152609752"></a>The catch block receives an error object (also known as an <em>exception</em>), which provides the following properties:</p>
        <dl>
        <dt><code>name</code></dt>
        <dd>
        <p><a data-type="indexterm" data-primary="name property" id="idm45475152606712"></a>A string that usually reflects the error subtype (as in “URIError”), but it may just be “Error.”</p>
        </dd>
        <dt><code>message</code></dt>
        <dd>
        <p><a data-type="indexterm" data-primary="message property" id="idm45475152579768"></a>A string that gives you a human-language description of the problem, like “URI malformed.”</p>
        </dd>
        <dt><code>stack</code></dt>
        <dd>
        <p><a data-type="indexterm" data-primary="stack property" id="idm45475152577544"></a>A string that lists the currently open functions on the stack, in order, from the most recent calls to the earlier ones. Depending on the browser, the <code>stack</code> property may include information about the location of the function (such as line number and filename) and the arguments the functions were called with.</p>
        </dd>
        </dl>
        <div data-type="warning" epub:type="warning"><h6>Warning</h6>
        <p>Be careful. There are a few other properties defined on the error object (like <code>description</code> and <code>lineNumber</code>) that only work in specific browsers. Don’t rely on these nonstandard properties when writing error-handling code, because they won’t work on all <span class="keep-together">browsers</span>.</p>
        </div>
        
        <p>If you pass the error object directly to the <code>console.log()</code> method (as in this example), you’ll get the information extracted from all three of these properties. It will look something like this, depending on the browser:</p>
        
        <pre data-type="programlisting">URIError: URI malformed
            at decodeURI (&lt;anonymous&gt;)
            at runTest (&lt;anonymous&gt;):14:15
            at &lt;anonymous&gt;:20:1</pre>
        
        <p>Here, a piece of top-level code written in the developer console (represented by the bottom <code>&lt;anonymous&gt;</code> in the call stack list) called a function named <code>runTest()</code>, which then used the code shown above to call <code>decodeURI()</code> with a bad URI, triggering the error that was then logged.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475152569064">
        <h2>Solution</h2>
        
        <p>Before you test your error-handling code, you need a routine that can cause an error to occur. For this example, we don’t want to consider syntax errors or any logical mistake that should realistically be caught when you’re writing your code (perhaps using a linter, as described in <a data-type="xref" href="ch01.html#using_eslint">“Enforcing Code Standards with a Linter”</a>). Instead, we want an operation that is <em>risky</em> because it relies on an outside resource and could fail due to no fault of your code.</p>
        
        <p>JavaScript is unusually tolerant of usage that would be considered an error in many other programming languages. Attempting to access a property that doesn’t exist gets an error-free value of <code>undefined</code>. The same is true if you go beyond the bounds of an array. JavaScript’s error tolerance is particularly apparent with math, where nonsensical calculations like multiplying a number by a string returns an error-free value of <code>NaN</code> (not a number), and dividing by zero returns the special value <code>Infinity</code>. Attempting to use the <code>decodeURI()</code> function is an example of an operation that can fail, in this case with a <code>UriError</code>.</p>
        <div data-type="note" epub:type="note"><h6>Note</h6>
        <p><a data-type="indexterm" data-primary="query string" id="idm45475152562024"></a><a data-type="indexterm" data-primary="decodeURI() function" id="idm45475152561096"></a><a data-type="indexterm" data-primary="encodeURI() function" id="idm45475152560424"></a>The <code>decodeURI()</code> and <code>encodeURI()</code> methods are designed to replace characters that aren’t allowed in web URLs with escape sequences that are acceptable, which is an important technique if you’re storing arbitrary data in the <em>query string</em> (the portion of the URL that follows the <code>?</code>). Attempting to reverse this encoding on a string that has not been properly encoded can fail—for example, if it includes a <code>%</code> character that should begin an escape sequence.</p>
        </div>
        
        <p>The act of catching an error prevents it from being an unhandled error. This means your code can continue (and in the case of a Node application, prevents your application from ending altogether). However, you should only catch errors that you understand and are prepared to deal with. You never use error-handling simply to suppress and ignore potential problems. <a data-type="xref" href="#unhandled_errors">“Detecting Unhandled Errors”</a> has more about the effect of unhandled errors.</p>
        
        <p><a data-type="indexterm" data-primary="try…catch block" id="idm45475152555080"></a>Although a <code>try...catch</code> block is the most common structure for error handling, you can optional add a <code>finally</code> section to the end. The code in the <code>finally</code> block always runs. It runs after the <code>try</code> block if no errors occurred, or after the <code>catch</code> block if an error was caught. It’s most commonly used as a place to put cleanup code that should run regardless of whether your code succeeded or failed.</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="k">try</code> <code class="p">{</code>
          <code class="kr">const</code> <code class="nx">uri</code> <code class="o">=</code> <code class="nb">decodeURI</code><code class="p">(</code><code class="s1">'http%test'</code><code class="p">);</code>
        
          <code class="c1">// We never get here</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'Success!'</code><code class="p">);</code>
        <code class="p">}</code>
        <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">error</code><code class="p">);</code>
        <code class="p">}</code>
        <code class="k">finally</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'The operation (and any error handling) is complete'</code><code class="p">);</code>
        <code class="p">}</code></pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475152452488">
        <h2>See Also</h2>
        
        <p><a data-type="xref" href="#catching_error_subtypes">“Catching Different Types of Errors”</a> shows how to selectively catch different error types. <a data-type="xref" href="#catching_async_errors">“Catching Asynchronous Errors”</a> shows how to catch errors that happen during asynchronous operations.<a data-type="indexterm" data-primary="" data-startref="ix_error_neutralizing" id="idm45475152492696"></a></p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Catching Different Types of Errors"><div class="sect1" id="catching_error_subtypes">
        <h1>Catching Different Types of Errors</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475152490008">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="catching different types" id="ix_error_diff_types"></a>You want to distinguish between different types of errors and handle them differently, or handle only specific types.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475152487080">
        <h2>Solution</h2>
        
        <p>Unlike many languages, JavaScript does not allow you to catch errors by type. <a data-type="indexterm" data-primary="instanceOf operator" id="idm45475152485784"></a>Instead, you must catch all errors (as usual), and then investigate the error with the <code>instanceof</code> operator:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="k">try</code> <code class="p">{</code>
          <code class="c1">// Some code that will raise an error</code>
        <code class="p">}</code>
        <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="k">if</code> <code class="p">(</code><code class="nx">error</code> <code class="k">instanceof</code> <code class="nx">RangeError</code><code class="p">)</code> <code class="p">{</code>
            <code class="c1">// Do something about the value being out of range</code>
          <code class="p">}</code>
          <code class="k">else</code> <code class="k">if</code> <code class="p">(</code><code class="nx">error</code> <code class="k">instanceof</code> <code class="nx">TypeError</code><code class="p">)</code> <code class="p">{</code>
            <code class="c1">// Do something about the value being the wrong type</code>
          <code class="p">}</code>
          <code class="k">else</code> <code class="p">{</code>
            <code class="c1">// Rethrow the error</code>
            <code class="k">throw</code> <code class="nx">error</code><code class="p">;</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        
        <p>Finally, if the error is not a type that you can handle, you should rethrow the error.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475152420216">
        <h2>Discussion</h2>
        
        <p>JavaScript has eight error types, which are represented by different error objects (see <a data-type="xref" href="#error_types">Table&nbsp;10-1</a>). You can check an error’s type to determine the kind of problem that occurred. This may indicate what actions you should take, or if you can carry out alternate code, retry an operation, or recover. <a data-type="indexterm" data-primary="errors (Error object)" data-secondary="list of types" id="idm45475152403512"></a>It may also provide more information about exactly what went wrong.</p>
        <table id="error_types">
        <caption><span class="label">Table 10-1. </span>Error objects</caption>
        <thead>
        <tr>
        <th>Error Type</th>
        <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td><p><code>RangeError</code></p></td>
        <td><p>Occurs when a numeric value is outside of its allowed range.</p></td>
        </tr>
        <tr>
        <td><p><code>ReferenceError</code></p></td>
        <td><p>Occurs when trying to assign a nonexistent object to a variable.</p></td>
        </tr>
        <tr>
        <td><p><code>SyntaxError</code></p></td>
        <td><p>Occurs when code has a clear syntactical error, like an extra <code>(</code> or missing <code>}</code>.</p></td>
        </tr>
        <tr>
        <td><p><code>TypeError</code></p></td>
        <td><p>Occurs when a value is not the right data type for a given operation.</p></td>
        </tr>
        <tr>
        <td><p><code>URIError</code></p></td>
        <td><p>Raised by problems escaping URLs with <code>decodeURI()</code> and other related functions.</p></td>
        </tr>
        <tr>
        <td><p><code>AggregateError</code></p></td>
        <td><p>Is a wrapper for multiple errors, which is useful for errors that occur asynchronously. An array of error objects is provided in the <code>errors</code> property.</p></td>
        </tr>
        <tr>
        <td><p><code>EvalError</code></p></td>
        <td><p>Meant to represent problems that occur with the built-in <code>eval()</code>, but it’s no longer used. Now, using <code>eval()</code> on syntactically invalid code will cause a <code>SyntaxError</code> to be thrown.</p></td>
        </tr>
        <tr>
        <td><p><code>InternalError</code></p></td>
        <td><p>Occurs for a variety of nonstandard cases, and is browser specific. For example, on Firefox an <code>InternalError</code> occurs if you exceed the recursion limit (by having a function call itself over and over again), while in Chrome the same condition is represented by a <code>RangeError</code>.</p></td>
        </tr>
        </tbody>
        </table>
        
        <p>In addition to these error types, you can also throw and catch your own custom error objects, as described in <a data-type="xref" href="#throwing_custom_errors">“Throwing a Custom Error”</a>.</p>
        
        <p>JavaScript only allows one <code>catch</code> block for every <code>try</code> block, which prevents you from catching errors by type. However, you can catch the standard <code>Error</code> object, examine its type with <code>instanceof</code>, and write conditional code to deal with it accordingly. When you use this approach, you must be careful not to accidentally suppress errors you can’t deal with.</p>
        
        <p><a data-type="indexterm" data-primary="RangeError" id="idm45475152376520"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="TypeError" id="idm45475152375592"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="RangeError" id="idm45475152374648"></a><a data-type="indexterm" data-primary="TypeError" id="idm45475152373704"></a>In the current example, the code explicitly handles the <code>RangeError</code> and <code>TypeError</code> type. <a data-type="indexterm" data-primary="throw statement" id="idm45475152371992"></a>If the error is something else, we assume there’s nothing practical we can do to resolve the problem. The error is then rethrown with the <code>throw</code> statement. When you use <code>throw</code>, it’s as if the same error occurred again. If your code is in a function, this allows the error to continue to bubble up the stack until it reaches some error-handling code that can deal with it appropriately. If there is no other error-handling that catches this error, it becomes an unhandled error, just as it would have if you hadn’t caught it in the first place. (See <a data-type="xref" href="#unhandled_errors">“Detecting Unhandled Errors”</a> for more about that.)</p>
        
        <p>In other words, rethrowing unknown errors gives you the same behavior you would have if you caught only specific exception types—which is the approach you would probably take if the JavaScript language supported it.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475152368280">
        <h2>See Also</h2>
        
        <p><a data-type="xref" href="#throwing_custom_errors">“Throwing a Custom Error”</a> shows how to create your own error class to indicate a custom error condition and pass along extra information about the error.<a data-type="indexterm" data-primary="" data-startref="ix_error_diff_types" id="idm45475152366104"></a></p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Catching Asynchronous Errors"><div class="sect1" id="catching_async_errors">
        <h1>Catching Asynchronous Errors</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475152341592">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="asynchronous programming" data-secondary="error handling" id="ix_async_prog_error"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="in asynchronous programming" data-secondary-sortas="asynchronous programming" id="ix_error_async_prog"></a>You want to add error handling but the risky operation is performed on a background thread.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475152337208">
        <h2>Solution</h2>
        
        <p>JavaScript APIs have more than one model of asynchronicity, and the way you handle errors depends on the function you’re using.</p>
        
        <p>If you’re using an older API, you may need to supply a callback function that will be called in the event of an error, or attach an event handler. The <code>XMLHttpRequest</code> object provides an <code>error</code> event to notify you about failed requests, for example:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kr">const</code> <code class="nx">request</code> <code class="o">=</code> <code class="k">new</code> <code class="nx">XMLHttpRequest</code><code class="p">();</code>
        
        <code class="nx">request</code><code class="p">.</code><code class="nx">onerror</code> <code class="o">=</code> <code class="kd">function</code> <code class="nx">errorHander</code><code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">error</code><code class="p">);</code>
        <code class="p">}</code>
        
        <code class="nx">request</code><code class="p">.</code><code class="nx">open</code><code class="p">(</code><code class="s1">'GET'</code><code class="p">,</code> <code class="s1">'http://noserver'</code><code class="p">);</code>
        <code class="nx">request</code><code class="p">.</code><code class="nx">send</code><code class="p">();</code></pre>
        
        <p>Here the call to <code>send()</code> triggers the asynchronous operation that leads to the error, but the actual error occurs on a separate thread. Adding a <code>try...catch</code> block around this statement won’t catch the problem. The best you can do is receive a notification through the <code>error</code> event.</p>
        
        <p><a data-type="indexterm" data-primary="promises (Promise object)" data-secondary="error handling" id="idm45475152298008"></a>If you’re using a promise-based API, you attach your error-handling function by calling <code>Promise.catch()</code>. Here’s an example with the Fetch API:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">fetch</code><code class="p">(</code><code class="s1">'http://noserver'</code><code class="p">)</code>
        <code class="p">.</code><code class="nx">then</code><code class="p">((</code><code class="nx">response</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'We did it, fam.'</code><code class="p">);</code>
        <code class="p">})</code>
        <code class="p">.</code><code class="k">catch</code><code class="p">((</code><code class="nx">error</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">error</code><code class="p">);</code>
        <code class="p">});</code></pre>
        
        <p>The code you write here will be triggered in the event of an unhandled error or a rejected promise. If you don’t catch an error that occurs in a promise, it will bubble up to your main application thread and trigger the <code>window.unhandledrejection</code> event, which is the promise-based equivalent to the <code>window.error</code> event (see <a data-type="xref" href="#unhandled_errors">“Detecting Unhandled Errors”</a>).</p>
        
        <p>Finally, if you’re using promises with the higher-level <code>async</code> and <code>await</code> model, you can use a traditional error-handling block. The <code>catch</code> section will be attached to the promise automatically with <code>Promise.catch()</code>. Here’s an example:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">async</code> <code class="kd">function</code> <code class="nx">doWork</code><code class="p">()</code> <code class="p">{</code>
          <code class="k">try</code> <code class="p">{</code>
            <code class="kr">const</code> <code class="nx">response</code> <code class="o">=</code> <code class="nx">await</code> <code class="nx">fetch</code><code class="p">(</code><code class="s1">'http://noserver'</code><code class="p">);</code>
          <code class="p">}</code>
          <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
            <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">error</code><code class="p">);</code>
          <code class="p">}</code>
        <code class="p">}</code>
        
        <code class="nx">doWork</code><code class="p">().</code><code class="nx">then</code><code class="p">(()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'All done'</code><code class="p">);</code>
        <code class="p">});</code></pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475152336616">
        <h2>Discussion</h2>
        
        <p>Putting error-handling code in the wrong place is a common mistake. Unfortunately, it’s not always obvious that your error-handling code is ineffective or will never run, although a linting tool (<a data-type="xref" href="ch01.html#using_eslint">“Enforcing Code Standards with a Linter”</a>) may alert you to the problem. The best solution is to test actual error conditions in your application, and verify that your error-handling code runs and mitigates them.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475152158024">
        <h2>See Also</h2>
        
        <p><a data-type="xref" href="ch09.html#async_call_with_promise">“Using a Function That Returns a Promise”</a> shows a complete example with the Fetch API and promise-based error handling. <a data-type="xref" href="ch09.html#using_await">“Waiting for a Promise to Finish with Await and Async”</a> shows a complete example with the Fetch API and <code>async</code> and <code>await</code> error handling.<a data-type="indexterm" data-primary="" data-startref="ix_error_async_prog" id="idm45475152154360"></a><a data-type="indexterm" data-primary="" data-startref="ix_async_prog_error" id="idm45475152153352"></a></p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Detecting Unhandled Errors"><div class="sect1" id="unhandled_errors">
        <h1>Detecting Unhandled Errors</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475152150664">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="detecting unhandled" id="ix_error_unhandled"></a>You want to catch errors that have not been handled in your code, possibly to create a diagnostic log.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475152147720">
        <h2>Solution</h2>
        
        <p>Handle the <code>window.error</code> event. Your event-handling function receives five parameters with error information. Along with an error object that represents the actual error, you also get a separate <code>message</code> parameter and location information (<code>source</code> with the URL of the script file, <code>lineno</code> with the line number where the error occurred, and <code>colno</code> with the column number).</p>
        
        <p>Here’s an example that tests this event:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="c1">// Attach the event handler</code>
        <code class="nb">window</code><code class="p">.</code><code class="nx">onerror</code> <code class="o">=</code> <code class="p">(</code><code class="nx">message</code><code class="p">,</code> <code class="nx">url</code><code class="p">,</code> <code class="nx">lineNo</code><code class="p">,</code> <code class="nx">columnNo</code><code class="p">,</code> <code class="nx">error</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="sb">`An unhandled error occurred in </code><code class="si">${</code><code class="nx">url</code><code class="si">}</code><code class="sb">`</code><code class="p">);</code>
        <code class="p">}</code>
        
        <code class="c1">// Cause an unhandled error</code>
        <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="kc">null</code><code class="p">.</code><code class="nx">length</code><code class="p">);</code></pre>
        
        <p>Note that to test this example, you need to use a sample test page. You can’t attach a function to the <code>window.error</code> event handler using the developer console.</p>
        <div data-type="note" epub:type="note"><h6>Note</h6>
        <p><a data-type="indexterm" data-primary="security issues" data-secondary="browser access to error details" id="idm45475152072888"></a><a data-type="indexterm" data-primary="browser" data-secondary="security and access to error details" id="idm45475152071720"></a>In some cases, the browser’s cross-origin security policy will prevent your JavaScript code from having access to the error details. One example is if you’re running your test page from the local filesystem instead of using a test server. In this situation, the <code>message</code> parameter will have the generic text “Script error,” and the <code>url</code>, <code>lineNo</code>, <code>columnNo</code>, and <code>error</code> properties will be blank. For more information, see <a href="https://oreil.ly/9MbGP">the <code>onerror</code> notes</a>.</p>
        </div>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475152066920">
        <h2>Discussion</h2>
        
        <p><a data-type="indexterm" data-primary="event handlers" data-secondary="window.error" id="idm45475152065288"></a><a data-type="indexterm" data-primary="window.error event handler" id="idm45475152064312"></a>Unhandled errors that occur on the main thread of your application bubble up the stack until they reach the top level of your code and—if it’s not handled there—trigger the <code>window.error</code> event in the browser.</p>
        
        <p>The <code>window.error</code> event is unusual in that it allows you to <em>cancel</em> the error, effectively suppressing it. To do that, you return <code>true</code> from the event-handling function. <a data-type="indexterm" data-primary="console.error() method" id="idm45475152061016"></a>If you don’t suppress an error, the browser’s default error-handler springs into action. It displays the error information in the developer console in bright red lettering, just as when you log it with the <code>console.error()</code> method. But if you return <code>true</code> from <code>window.error</code>, the error vanishes, and no trace of it will appear in the developer console.</p>
        
        <p>Other than that, there’s no practical difference between suppressing or allowing an error in your <code>window.error</code> event handler. By the time an error has triggered the <span class="keep-together"><code>window.error</code></span> event, your code has already been halted and the stack has been unwound. However, this doesn’t stop your web page from working. As soon as another event occurs (for example, you click a button), JavaScript begins executing your code again.</p>
        <div data-type="note" epub:type="note"><h6>Note</h6>
        <p>Modern practice discourages us from hiding errors, even from the developer console, unless there’s a very good reason. One possibility might be you’re replacing the default error display with something that’s fine-tuned to your application, and provides more useful information or removes information you don’t want to make visible to users.</p>
        </div>
        
        <p>You can use your <code>window.error</code> event handler to execute any type of JavaScript code. For example, you could log the error to a local data store or even send it to a web server using the Fetch API. If an error occurs <em>during</em> the <code>window.error</code> event handler, the event handler won’t be triggered again. It will simply pass straight to the browser’s default error handler and show up in the developer console.</p>
        
        <p><a data-type="indexterm" data-primary="asynchronous programming" data-secondary="error handling" id="idm45475152052840"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="in asynchronous programming" data-secondary-sortas="asynchronous programming" id="idm45475152051800"></a>For asynchronous code, errors are handled differently. For older callback-based APIs, there usually are no errors. Instead, these APIs use callbacks to notify your code about error conditions (see <a data-type="xref" href="#catching_async_errors">“Catching Asynchronous Errors”</a>). <a data-type="indexterm" data-primary="events" data-secondary="window.unhandledrejection" id="idm45475152049416"></a><a data-type="indexterm" data-primary="window.unhandledrejection event" id="idm45475152048424"></a>But for promise-based APIs, unhandled errors bubble up and will trigger the <code>window.unhandledrejection</code> event:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="c1">// Attach the event handler</code>
        <code class="nb">window</code><code class="p">.</code><code class="nx">onunhandledrejection</code> <code class="o">=</code> <code class="p">(</code><code class="nx">e</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="nx">e</code><code class="p">.</code><code class="nx">reason</code><code class="p">);</code>
        <code class="p">}</code>
        
        <code class="c1">// Create a promise that will cause an unhandled asynchronous error</code>
        <code class="kr">const</code> <code class="nx">faultyPromise</code> <code class="o">=</code> <code class="k">new</code> <code class="nb">Promise</code><code class="p">(()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="k">throw</code> <code class="k">new</code> <code class="nb">Error</code><code class="p">(</code><code class="s1">'Disaster strikes!'</code><code class="p">);</code>
        <code class="p">});</code>
        
        <code class="c1">// Create a promise that rejects (also triggers window.onunhandledrejection)</code>
        <code class="kr">const</code> <code class="nx">rejectedPromise</code> <code class="o">=</code> <code class="k">new</code> <code class="nb">Promise</code><code class="p">((</code><code class="nx">resolve</code><code class="p">,</code> <code class="nx">reject</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">reject</code><code class="p">(</code><code class="k">new</code> <code class="nb">Error</code><code class="p">(</code><code class="s1">'Another disaster strikes!'</code><code class="p">));</code>
        <code class="p">});</code></pre>
        
        <p><a data-type="indexterm" data-primary="promises (Promise object)" data-secondary="error handling" id="idm45475152044568"></a>The <code>unhandledrejection</code> event passes a single object with event properties to your event handler. The <code>reason</code> property (used in the example above) has the unhandled error object, or whatever object was passed to <code>Promise.reject()</code> if the promise was manually rejected. You can also get the underlying <code>Promise</code> object from the <code>promise</code> property.</p>
        
        <p>Like <code>window.error</code>, <code>window.unhandledrejection</code> is a cancellable event. However, it uses a different, more modern convention for cancellation. <a data-type="indexterm" data-primary="preventDefault() method" id="idm45475151951560"></a>Instead of returning <code>true</code>, you can use the <code>preventDefault()</code> method of the object with the event arguments. Here’s an example that shows a message when an unhanded promise error occurs, but hides the automatic error logging:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nb">window</code><code class="p">.</code><code class="nx">onunhandledrejection</code> <code class="o">=</code> <code class="p">(</code><code class="nx">e</code><code class="p">)</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="s1">'An error occurred, but we won\'t tell you what it was'</code><code class="p">);</code>
        
          <code class="c1">// Cancel the default error handling</code>
          <code class="nx">e</code><code class="p">.</code><code class="nx">preventDefault</code><code class="p">();</code>
        <code class="p">}</code></pre>
        <div data-type="tip"><h6>Tip</h6>
        <p>You might think that the unhandled exception events are a good place to put your logging code. Sometimes they are. But usually, you’ll want to catch errors closer to where they occur, log them there, and rethrow them if necessary. However, the unhandled exception events are always a good way to find risky bits of code that need exception-handling logic but don’t have it.<a data-type="indexterm" data-primary="" data-startref="ix_error_unhandled" id="idm45475151862104"></a></p>
        </div>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Extra: Logging Tools"><div class="sect2" id="logging_tools">
        <h2>Extra: Logging Tools</h2>
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="logging tools" id="idm45475151927464"></a>Broadly speaking, there are two times you catch errors: when you’re testing your code and you’re able to fix them, and when your application is in production and you want to know what went wrong. In the first case, logging is simple—your goal is to detect the problem and fix it. Often your logging simply involves calling <code>console.log()</code>. In the latter case, you need to investigate a problem that may be occurring sporadically, in a specific environment, and in front of an end user. Now you need a way to detect the problem and report the details back to you.</p>
        
        <p>You could handle the <code>window.error</code> and <code>window.unhandledrejection</code> events, and then write the details to some sort of storage. For example, you could save error information in the <code>localStorage</code> object so it persists for longer than the current browser session. You could use <code>fetch()</code> to send the details to a web API on your server. If you’re building a Node application, you could write the details to a file or database on the server. You could add extra contextual information, like system details, a priority level, and a timestamp. But as your logging needs grow, you may want to consider using an open source logging tool rather than roll your own <span class="keep-together">solution</span>.</p>
        
        <p><a data-type="indexterm" data-primary="abstraction layers, logging" id="idm45475151921656"></a>A good logging tool gives you an <em>abstraction layer</em> over your logging. That means you’ll log messages (in much the same way you call the usual <code>console.log()</code> method), without thinking about where that log is or how it’s implemented. While you’re testing, the logging layer might just output your messages to the console. But when your application is deployed, the logging layer might ignore low-level messages entirely while sending the important ones somewhere else, such as to a remote web server. The logging tool can implement advanced features, like batching, which improves performance when multiple messages are logged to a remote site in quick succession.</p>
        
        <p>There’s a dizzying array of logging libraries for JavaScript applications, including Winston, Bunyan, Log4js, Loglevel, Debug, Pino, and many more. Some are designed specifically for Node applications, but many can also work with web page code in a browser.</p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Throwing a Standard Error"><div class="sect1" id="throwing_errors">
        <h1>Throwing a Standard Error</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475151917080">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="throwing standard error object" id="ix_error_stand_obj"></a>You want to indicate an error condition by throwing an error object.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475151941672">
        <h2>Solution</h2>
        
        <p><a data-type="indexterm" data-primary="message property" id="idm45475151940504"></a>Create an instance of the <code>Error</code> object, passing a short description of the problem to the constructor, which is used for the <code>message</code> property. <a data-type="indexterm" data-primary="throw statement" id="idm45475151938600"></a>Throw the <code>Error</code> object with the <code>throw</code> statement. Your code can then catch this <code>Error</code> object just like it catches any other type of JavaScript error:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kd">function</code> <code class="nx">strictDivision</code><code class="p">(</code><code class="nx">number</code><code class="p">,</code> <code class="nx">divisor</code><code class="p">)</code> <code class="p">{</code>
          <code class="k">if</code> <code class="p">(</code><code class="nx">divisor</code> <code class="o">==</code> <code class="mi">0</code><code class="p">)</code> <code class="p">{</code>
            <code class="k">throw</code> <code class="k">new</code> <code class="nb">Error</code><code class="p">(</code><code class="s1">'Dividing by zero is not allowed'</code><code class="p">);</code>
          <code class="p">}</code>
          <code class="k">else</code> <code class="p">{</code>
            <code class="k">return</code> <code class="nx">number</code><code class="o">/</code><code class="nx">divisor</code><code class="p">;</code>
          <code class="p">}</code>
        <code class="p">}</code>
        
        <code class="c1">// Catch the error</code>
        <code class="k">try</code> <code class="p">{</code>
          <code class="kr">const</code> <code class="nx">result</code> <code class="o">=</code> <code class="nx">strictDivision</code><code class="p">(</code><code class="mi">42</code><code class="p">,</code> <code class="mi">0</code><code class="p">);</code>
        <code class="p">}</code>
        <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="c1">// Shows the custom error message</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="sb">`Error: </code><code class="si">${</code><code class="nx">error</code><code class="p">.</code><code class="nx">message</code><code class="si">}</code><code class="sb">`</code><code class="p">);</code>
        <code class="p">}</code></pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475151934488">
        <h2>Discussion</h2>
        
        <p>There are two ways to create an <code>Error</code> object. You can use the <code>new</code> keyword to create it, as in the solution. <a data-type="indexterm" data-primary="Error() function" id="idm45475151770072"></a>Or (less commonly), you can call <code>Error()</code> like a function, which has the same result:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="c1">// Standard error-throwing</code>
        <code class="k">throw</code> <code class="k">new</code> <code class="nb">Error</code><code class="p">(</code><code class="sb">`Dividing by zero is not allowed`</code><code class="p">);</code>
        
        <code class="c1">// An equivalent approach</code>
        <code class="k">throw</code> <code class="nb">Error</code><code class="p">(</code><code class="sb">`Dividing by zero is not allowed`</code><code class="p">);</code></pre>
        
        <p>The <code>Error</code> object has the standard error properties, including the <code>message</code> you set, a <code>name</code> (unhelpfully set to “Error”), and <code>stack</code> (the stack trace that pinpoints where the error occurred).</p>
        <div data-type="warning" epub:type="warning"><h6>Warning</h6>
        <p>JavaScript also allows code to use <code>throw</code> with nonerror objects (like strings). This usage is nonstandard and can cause problems in exception-handling code that expects properties like <code>name</code> and <code>message</code>. As a rule of thumb, do not throw nonexception objects.</p>
        </div>
        
        <p>Sometimes, you may be able to repurpose a more specific error subtype. Most of JavaScript’s built-in error types (listed in <a data-type="xref" href="#error_types">Table&nbsp;10-1</a>) are for specialized cases and are not suitable for custom code. But a couple are potentially useful. <a data-type="indexterm" data-primary="RangeError" id="idm45475151750344"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="RangeError" id="idm45475151749672"></a>You can use <code>RangeError</code> if a function receives a value that falls outside of the acceptable numeric range. Make sure to include an informative error message that includes the given value and the expected range:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kd">function</code> <code class="nx">setAge</code><code class="p">(</code><code class="nx">age</code><code class="p">)</code> <code class="p">{</code>
          <code class="kr">const</code> <code class="nx">upper</code> <code class="o">=</code> <code class="mi">125</code><code class="p">;</code>
          <code class="kr">const</code> <code class="nx">lower</code> <code class="o">=</code> <code class="mi">18</code><code class="p">;</code>
          <code class="k">if</code> <code class="p">(</code><code class="nx">age</code> <code class="o">&gt;</code> <code class="mi">125</code> <code class="o">||</code> <code class="nx">age</code> <code class="o">&lt;</code> <code class="mi">18</code><code class="p">)</code> <code class="p">{</code>
            <code class="k">throw</code> <code class="k">new</code> <code class="nx">RangeError</code><code class="p">(</code>
             <code class="sb">`Age [</code><code class="si">${</code><code class="nx">age</code><code class="si">}</code><code class="sb">] is out of the acceptable range of </code><code class="si">${</code><code class="nx">lower</code><code class="si">}</code><code class="sb"> to </code><code class="si">${</code><code class="nx">upper</code><code class="si">}</code><code class="sb">.`</code><code class="p">);</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        
        <p><code>RangeError</code> is specifically intended for numeric values. However, you might use <code>TypeError</code> to indicate errors where the supplied value was of the wrong type. It’s up to you to decide what constitutes a “wrong” type; perhaps a string when you expect a number (test that with <code>typeof</code>), or the wrong sort of object (test that with <code>instanceof</code>).</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kd">function</code> <code class="nx">calculateValue</code><code class="p">(</code><code class="nx">num</code><code class="p">)</code> <code class="p">{</code>
          <code class="k">if</code> <code class="p">(</code><code class="k">typeof</code> <code class="nx">num</code> <code class="o">!==</code> <code class="s1">'number'</code><code class="p">)</code> <code class="p">{</code>
            <code class="k">throw</code> <code class="k">new</code> <code class="nx">TypeError</code><code class="p">(</code><code class="sb">`Value [</code><code class="si">${</code><code class="nx">num</code><code class="si">}</code><code class="sb">] is not a number.`</code><code class="p">);</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        
        <p><a data-type="indexterm" data-primary="ReferenceError" id="idm45475151607656"></a><a data-type="indexterm" data-primary="SyntaxError" id="idm45475151618184"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="ReferenceError" id="idm45475151617576"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="SyntaxError" id="idm45475151616632"></a>Less useful error subtypes that you might consider include <code>ReferenceError</code> (if you receive a <code>null</code> reference or <code>undefined</code> value when you expect an object) or <code>SyntaxError</code> (for instance, if you’re parsing some type of string content that doesn’t follow the rules you’ve established). To get more specific about other error conditions, consider making your own error class (<a data-type="xref" href="#throwing_custom_errors">“Throwing a Custom Error”</a>).</p>
        
        <p>Compared to many stricter languages, JavaScript uses errors sparingly. When designing your own libraries, it’s usually best to follow that convention. Don’t use exceptions for cases that JavaScript would ordinarily tolerate (like implicit type conversions). Don’t use errors to notify the calling code about nonexceptional cases—in other words, things that are likely to happen during normal operation, like invalid user input. <em>Do</em> use exceptions to prevent code from continuing with an operation that will fail because something hasn’t been initialized correctly.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475151934024">
        <h2>See Also</h2>
        
        <p><a data-type="xref" href="#throwing_custom_errors">“Throwing a Custom Error”</a> explains how to create your own error object.<a data-type="indexterm" data-primary="" data-startref="ix_error_stand_obj" id="idm45475151571512"></a></p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Throwing a Custom Error"><div class="sect1" id="throwing_custom_errors">
        <h1>Throwing a Custom Error</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475151568824">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="throw statement" id="ix_throw_state"></a><a data-type="indexterm" data-primary="errors (Error object)" data-secondary="throwing custom error object" id="ix_error_custom_obj"></a>You want to indicate a specific error condition by throwing a custom error object.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475151565048">
        <h2>Solution</h2>
        
        <p><a data-type="indexterm" data-primary="Error class" id="idm45475151563640"></a>Create a class that inherits from the standard <code>Error</code> class. <a data-type="indexterm" data-primary="super() keyword" id="idm45475151562200"></a>The constructor should accept the descriptive text for the <code>message</code> property, and use <code>super()</code> to call the base <code>Error</code> class constructor with the message. Here’s a bare minimum custom error, with the code that throws it:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kr">class</code> <code class="nx">CustomError</code> <code class="kr">extends</code> <code class="nb">Error</code> <code class="p">{</code>
          <code class="nx">constructor</code><code class="p">(</code><code class="nx">message</code><code class="p">)</code> <code class="p">{</code>
            <code class="kr">super</code><code class="p">(</code><code class="nx">message</code><code class="p">);</code>
            <code class="k">this</code><code class="p">.</code><code class="nx">name</code> <code class="o">=</code> <code class="s1">'CustomError'</code><code class="p">;</code>
        
            <code class="c1">// Optional improvement: clean up the stack trace, if supported</code>
            <code class="k">if</code> <code class="p">(</code><code class="nb">Error</code><code class="p">.</code><code class="nx">captureStackTrace</code><code class="p">)</code> <code class="p">{</code>
              <code class="nb">Error</code><code class="p">.</code><code class="nx">captureStackTrace</code><code class="p">(</code><code class="k">this</code><code class="p">,</code> <code class="nx">CustomError</code><code class="p">);</code>
            <code class="p">}</code>
          <code class="p">}</code>
        <code class="p">}</code>
        
        <code class="c1">// Try raising this error</code>
        <code class="k">throw</code> <code class="k">new</code> <code class="nx">CustomError</code><code class="p">(</code><code class="s1">'An application-specific problem occurred'</code><code class="p">);</code></pre>
        
        <p><a data-type="indexterm" data-primary="captureStackTrace() method" id="idm45475151558728"></a>There’s one more recommended, but optional, refinement. You can use the static <code>Error.captureStackTrace()</code> method to clean up the stack trace slightly. (Technically, <code>captureStackTrace()</code> ensures that the call to the error constructor doesn’t appear in the stack trace that’s stored in the <code>Error.stack</code> property.)</p>
        
        <p>You can also add custom properties to pass extra information about the error condition. Here’s an example that stores a <code>productID</code> after a failed lookup:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kr">class</code> <code class="nx">ProductNotFound</code> <code class="kr">extends</code> <code class="nb">Error</code> <code class="p">{</code>
          <code class="nx">constructor</code><code class="p">(</code><code class="nx">missingProductID</code><code class="p">)</code> <code class="p">{</code>
            <code class="kr">super</code><code class="p">(</code><code class="sb">`Product </code><code class="si">${</code><code class="nx">missingProductID</code><code class="si">}</code><code class="sb"> does not exist in the catalog`</code><code class="p">);</code>
        
            <code class="k">this</code><code class="p">.</code><code class="nx">name</code> <code class="o">=</code> <code class="s1">'ProductNotFound'</code><code class="p">;</code>
            <code class="k">this</code><code class="p">.</code><code class="nx">productID</code> <code class="o">=</code> <code class="nx">missingProductID</code><code class="p">;</code>
        
            <code class="k">if</code> <code class="p">(</code><code class="nb">Error</code><code class="p">.</code><code class="nx">captureStackTrace</code><code class="p">)</code> <code class="p">{</code>
              <code class="nb">Error</code><code class="p">.</code><code class="nx">captureStackTrace</code><code class="p">(</code><code class="k">this</code><code class="p">,</code> <code class="nx">ProductNotFound</code><code class="p">);</code>
            <code class="p">}</code>
          <code class="p">}</code>
        <code class="p">}</code>
        
        <code class="k">try</code> <code class="p">{</code>
          <code class="k">throw</code> <code class="k">new</code> <code class="nx">ProductNotFound</code><code class="p">(</code><code class="mi">420</code><code class="p">);</code>
        <code class="p">}</code>
        <code class="k">catch</code> <code class="p">(</code><code class="nx">error</code><code class="p">)</code> <code class="p">{</code>
          <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="sb">`An error occured with the message: </code><code class="si">${</code><code class="nx">error</code><code class="p">.</code><code class="nx">message</code><code class="si">}</code><code class="sb">`</code><code class="p">);</code>
        
          <code class="k">if</code> <code class="p">(</code><code class="nx">error</code> <code class="k">instanceof</code> <code class="nx">ProductNotFound</code><code class="p">)</code> <code class="p">{</code>
            <code class="nx">console</code><code class="p">.</code><code class="nx">log</code><code class="p">(</code><code class="sb">`Missing: </code><code class="si">${</code><code class="nx">error</code><code class="p">.</code><code class="nx">productID</code><code class="si">}</code><code class="sb">`</code><code class="p">);</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475151491736">
        <h2>Discussion</h2>
        
        <p>When creating custom <code>Error</code> classes, we should keep in mind two possibly competing concerns: staying within the bounds of a typical JavaScript error, and expressing enough information for our customized error condition. In the former case, do not attempt to recreate the errors or exceptions of your second favorite language. Do not overextend JavaScript’s <code>Error</code> type with unnecessary methods and extra functionality.</p>
        
        <p>When you create a custom error, there are a few conventions to keep in mind:</p>
        
        <ul>
        <li>
        <p>Use the class name to indicate the error type, and set the <code>name</code> property to match. This is important if any code checks the <code>name</code> to determine the type of error (rather than using <code>instanceof</code>). It also persists even if the error object is serialized to JSON, and it appears in the error’s default string representation and the developer console.</p>
        </li>
        <li>
        <p>In the constructor, put your custom properties first in the parameter list. If you include a <code>message</code> parameter, it should be the last parameter.</p>
        </li>
        <li>
        <p>In the constructor, call <code>super()</code> and pass the <code>message</code> to the base class <span class="keep-together">constructor.</span></p>
        </li>
        <li>
        <p>As a nicety, properly set the stack trace. Check for the <code>captureStackTrace()</code> method, and, if present, call it, passing a reference to the current instance (as <code>this</code>) and your custom error class.</p>
        </li>
        </ul>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475151354728">
        <h2>See Also</h2>
        
        <p>To learn more about inheritance and the <code>extends</code> keyword, see <a data-type="xref" href="ch08.html#custom_class_inheritance">“Inheriting Functionality from Another Class”</a>.<a data-type="indexterm" data-primary="" data-startref="ix_errors_ch10" id="idm45475151352088"></a><a data-type="indexterm" data-primary="" data-startref="ix_error_custom_obj" id="idm45475151351112"></a><a data-type="indexterm" data-primary="" data-startref="ix_throw_state" id="idm45475151350168"></a></p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Writing Unit Tests for Your Code"><div class="sect1" id="unit_testing">
        <h1>Writing Unit Tests for Your Code</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475151347480">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="unit testing" data-secondary="writing tests with Jest" id="ix_unit_test_write"></a><a data-type="indexterm" data-primary="testing" data-secondary="writing unit tests" id="ix_test_write_unit"></a><a data-type="indexterm" data-primary="testing" id="ix_testing_ch10"></a>You want to use automated tests to ensure your code matches your design criteria now and in the future.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475151342376">
        <h2>Solution</h2>
        
        <p><a data-type="indexterm" data-primary="functions" data-secondary="Jest’s matcher functions" id="ix_functions_jest"></a><a data-type="indexterm" data-primary="Jest" id="ix_jest_test"></a>Use a tool like Jest to write unit tests for your code at the earliest possible stage.</p>
        
        <p>The easiest way to install Jest is with npm (<a data-type="xref" href="ch01.html#installing_npm_package">“Downloading a Package with npm”</a>). Open a terminal window in your project folder, and create the <em>package.json</em> configuration file if you don’t already have it with <code>npm init</code>:</p>
        
        <pre data-type="programlisting">$ npm init -y</pre>
        
        <p>Next, install Jest using the <code>--save-dev</code> parameter so that it’s only included in development builds:</p>
        
        <pre data-type="programlisting">$ npm install --save-dev jest</pre>
        
        <p>Now you need to find some code to test. Let’s say you have a file named <em>factorialize.js</em>, with the <code>factorialize()</code> function shown here:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kd">function</code> <code class="nx">factorialize</code><code class="p">(</code><code class="nx">number</code><code class="p">)</code> <code class="p">{</code>
          <code class="k">if</code> <code class="p">(</code><code class="nx">number</code> <code class="o">&lt;</code> <code class="mi">0</code><code class="p">)</code> <code class="p">{</code>
            <code class="k">throw</code> <code class="k">new</code> <code class="nx">RangeError</code><code class="p">(</code><code class="s1">'Factorials are only defined for positive numbers'</code><code class="p">);</code>
          <code class="p">}</code>
          <code class="k">else</code> <code class="k">if</code> <code class="p">(</code><code class="nx">number</code> <code class="o">!=</code> <code class="nb">Math</code><code class="p">.</code><code class="nx">trunc</code><code class="p">(</code><code class="nx">number</code><code class="p">))</code> <code class="p">{</code>
            <code class="k">throw</code> <code class="k">new</code> <code class="nx">RangeError</code><code class="p">(</code><code class="s1">'Factorials are only defined for integers'</code><code class="p">);</code>
          <code class="p">}</code>
          <code class="k">else</code> <code class="p">{</code>
            <code class="k">if</code> <code class="p">(</code><code class="nx">number</code> <code class="o">==</code> <code class="mi">0</code> <code class="o">||</code> <code class="nx">number</code> <code class="o">==</code> <code class="mi">1</code><code class="p">)</code> <code class="p">{</code>
              <code class="k">return</code> <code class="mi">1</code><code class="p">;</code>
            <code class="p">}</code>
            <code class="k">else</code> <code class="p">{</code>
              <code class="kd">let</code> <code class="nx">result</code> <code class="o">=</code> <code class="nx">number</code><code class="p">;</code>
              <code class="k">while</code> <code class="p">(</code><code class="nx">number</code> <code class="o">&gt;</code> <code class="mi">1</code><code class="p">)</code> <code class="p">{</code>
                <code class="nx">number</code><code class="o">--</code><code class="p">;</code>
                <code class="nx">result</code> <code class="o">*=</code> <code class="nx">number</code><code class="p">;</code>
              <code class="p">}</code>
              <code class="k">return</code> <code class="nx">result</code><code class="p">;</code>
            <code class="p">}</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        
        <p>To make this function accessible to Jest, you need to export the <code>factorialze()</code> function by adding this line to the end of the file:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kr">export</code> <code class="p">{</code><code class="nx">factorialize</code><code class="p">}</code></pre>
        <div data-type="note" epub:type="note"><h6>Note</h6>
        <p><a data-type="indexterm" data-primary="CommonJS" id="idm45475151161944"></a><a data-type="indexterm" data-primary="ES6 (ECMAScript 2015)" data-secondary="unit tests of code" id="idm45475151161080"></a>Jest assumes you’re using the Node module standard (CommonJS). <a data-type="indexterm" data-primary="Babel" id="idm45475151160008"></a>If you’re already using the newer ES6 module standard, you need to use Babel, a JavaScript transpilation tool, to convert your module references before Jest processes your code. This sounds complicated, but the <code>plugin-transform-modules-commonjs</code> module will take care of most of the work. To see the completely configured solution both ways (with CommonJS modules or ES6 modules), refer to the sample code. For more about CommonJS modules, see <a data-type="xref" href="ch18.html#converting_library_node_module">“Converting Your Library into a Node Module”</a>. For more about ES6 modules, see <a data-type="xref" href="ch08.html#using_es6_modules">“Organizing Your JavaScript Classes with Modules”</a>.</p>
        </div>
        
        <p><a data-type="indexterm" data-primary="files" data-secondary="test.js file" id="idm45475151178776"></a><a data-type="indexterm" data-primary="test.js file" id="idm45475151177800"></a>Now you need to create your test file. In Jest, test files have the extension <em>.test.js</em>. In this case, that means you need to create a new file named <em>factorialize.test.js</em>. This file then imports the function you want to test:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="kr">import</code> <code class="p">{</code><code class="nx">factorialize</code><code class="p">}</code> <code class="nx">from</code> <code class="s1">'./factorialize.js'</code><code class="p">;</code></pre>
        
        <p>The rest of your test file defines the test you want to run. The simplest approach to testing is to start by verifying that your function works the way you expect. For example, you can write a Jest test that verifies that <code>factorialize()</code> returns the correct information for a few representative cases. Here’s an example that checks that 10! is 3,628,800:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">test</code><code class="p">(</code><code class="s1">'10! is 3628800'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="mi">10</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">3628800</code><code class="p">);</code>
        <code class="p">});</code></pre>
        
        <p><a data-type="indexterm" data-primary="test() function" id="idm45475151041512"></a><a data-type="indexterm" data-primary="code" data-secondary="unit tests of" id="idm45475151129336"></a>Jest’s <code>test()</code> function creates a named test. The name allows you to identify tests in the test report, so you know exactly which tests succeeded and which ones failed. <a data-type="indexterm" data-primary="expect() function" id="idm45475151127736"></a>The test in this example uses Jest’s <code>expect()</code> function, which calls your code (in this case, the <code>factorialize()</code> function) and then evaluates the result with <code>toBe()</code>. <a data-type="indexterm" data-primary="matcher functions" id="idm45475151062760"></a><a data-type="indexterm" data-primary="toBe() function" id="idm45475151062024"></a>Technically, <code>toBe()</code> is one of several Jest <em>matcher functions</em>. It determines whether the code passes or fails the test.</p>
        
        <p>To run this test, you need to use Jest. You can run it from the command line, with your test file and the help of npm’s package runner, npx. In this example, you would use this command in the terminal:</p>
        
        <pre data-type="programlisting">$ npx jest factorialize.test.js</pre>
        
        <p>which runs the single test you’ve written and generates a report like this:</p>
        
        <pre data-type="programlisting">PASS  ./factorialize.test.js
         √ 10! is 3628800 (4 ms)
        
        Test Suites: 1 passed, 1 total
        Tests:       1 passed, 1 total
        Snapshots:   0 total
        Time:        2.725 s, estimated 3 s
        
        Ran all test suites matching /factorialize.test.js</pre>
        
        <p>More commonly, you’ll add Jest to the <code>scripts</code> section of your <em>package.json</em> file so it can run all your tests automatically:</p>
        
        <pre data-type="programlisting" data-code-language="json"><code class="p">{</code>
          <code class="nt">"scripts"</code><code class="p">:</code> <code class="p">{</code>
            <code class="nt">"test"</code><code class="p">:</code> <code class="s2">"jest"</code>
          <code class="p">}</code>
        <code class="p">}</code></pre>
        
        <p>Now you can ask Jest to run all the tests (the <em>.test.js</em> files) in your project folder.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475151341464">
        <h2>Discussion</h2>
        
        <p>There are multiple types of tests, such as tests for security, usability, and performance, but the most basic form of testing is <em>unit testing</em>. Unit testing consists of performing tests of discrete source code units, and verifying that those units behave as expected. In JavaScript, the most common unit for unit testing is a function.</p>
        
        <p><a data-type="indexterm" data-primary="testing" data-secondary="assertion tests" id="idm45475151045048"></a><a data-type="indexterm" data-primary="assertion tests" id="idm45475151019928"></a>Although there are many possible testing frameworks (Jest, Mocha, Jasmine, Karma, and more), most of them use a similar syntax. In Jest, everything revolves around a <code>test()</code> function that takes two arguments. The first argument is a label for the test, which appears in the test report. The second argument is a function that includes one or more test assertions—claims that will either be successfully proved true (a pass) or false (a fail):</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">test</code><code class="p">(</code><code class="s1">'Some test name'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="c1">// Test assertions go here</code>
        <code class="p">});</code></pre>
        
        <p>To create test assertions, you use the <code>expect()</code> function, which is the lynchpin of Jest. It works in conjunction with a matching function like <code>toBe()</code> that evaluates the results from your test call:</p>
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">test</code><code class="p">(</code><code class="s1">'10! is 3628800'</code><code class="p">,</code><code> </code><code class="p">(</code><code class="p">)</code><code> </code><code class="o">=&gt;</code><code> </code><code class="p">{</code><code>
          </code><strong><code class="nx">expect</code></strong><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="mi">10</code><code class="p">)</code><code class="p">)</code><code class="p">.</code><strong><code class="nx">toBe</code></strong><code class="p">(</code><code class="mi">3628800</code><code class="p">)</code><code class="p">;</code><code>
        </code><code class="p">}</code><code class="p">)</code><code class="p">;</code><code>
        </code></pre>
        
        <p>This example demonstrates a single test of the <code>factorialize()</code> function. But the goal of the test writer is broader. You need to choose a representative group of tests—ones that check multiple values and capture boundary conditions where possible. For example, with the <code>factorialize()</code> function test, it makes sense to test how the function deals with nonnumeric input, negative values, 0, very large values, and so on.</p>
        
        <p>The following code shows a more complete test suite. It checks the results of five different calls to <code>factorialize()</code>. <a data-type="indexterm" data-primary="describe() function" id="idm45475150932504"></a>These calls are all grouped into one test suite using <code>describe()</code>. The <code>describe()</code> function simply lets you label a collection of related test calls. In this example, <code>describe()</code> is grouping calls to the same function, but you might also use it to group calls that use the same set of sample data:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">describe</code><code class="p">(</code><code class="s1">'factorialize() function tests'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">test</code><code class="p">(</code><code class="s1">'0! is 1'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="mi">0</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">1</code><code class="p">);</code>
          <code class="p">});</code>
          <code class="nx">test</code><code class="p">(</code><code class="s1">'1! is 1'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="mi">1</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">1</code><code class="p">);</code>
          <code class="p">});</code>
          <code class="nx">test</code><code class="p">(</code><code class="s1">'10! is 3628800'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="mi">10</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">3628800</code><code class="p">);</code>
          <code class="p">});</code>
          <code class="nx">test</code><code class="p">(</code><code class="s1">'"5"! is 120'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="s1">'5'</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">120</code><code class="p">);</code>
          <code class="p">});</code>
          <code class="nx">test</code><code class="p">(</code><code class="s1">'NaN is 0'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">expect</code><code class="p">(</code><code class="nx">factorialize</code><code class="p">(</code><code class="kc">NaN</code><code class="p">)).</code><code class="nx">toBe</code><code class="p">(</code><code class="mi">0</code><code class="p">);</code>
          <code class="p">});</code>
        <code class="p">});</code></pre>
        
        <p>When you run this test, you’ll find that the final test fails. It expects the call <code>factorialize(NaN)</code> to return <code>0</code>, but it actually throws an error, as the test log makes clear:</p>
        
        <pre data-type="programlisting"> FAIL  ./factorialize.test.js
          factorialize() function tests
            √ 0! is 1 (3 ms)
            √ 1! is 1
            √ 10! is 3628800
            √ "5"! is 120
            × NaN is 0 (3 ms)
        
          ● factorialize() function tests › NaN is 0
        
            RangeError: Factorials are only defined for integers
        
              4 |   }
              5 |   if (number != Math.trunc(number)) {
            &gt; 6 |     throw new RangeError('Factorials are only defined for integers');
                |           ^
              7 |   }
              8 |   else {
              9 |     if (number == 0 || number == 1) {
        
              at factorialize (factorialize.js:6:11)
              at Object.&lt;anonymous&gt; (factorialize.test.js:17:12)
        
        Test Suites: 1 failed, 1 total
        Tests:       1 failed, 4 passed, 5 total
        Snapshots:   0 total
        Time:        2.833 s
        Ran all test suites.</pre>
        
        <p><a data-type="indexterm" data-primary="unit testing" data-secondary="matcher functions list" id="idm45475150814632"></a><a data-type="indexterm" data-primary="matcher functions" id="idm45475150813544"></a><a data-type="indexterm" data-primary="testing" data-secondary="matcher functions list" id="idm45475150812872"></a>Right now, every test you’ve seen uses the <code>toBe()</code> matching function to check for an exact value. But Jest, like all testing frameworks, lets you use different types of rules. For example, you could check that a number falls in a specific range, that text matches a certain pattern, or that a value isn’t null. <a data-type="xref" href="#jest_matchers">Table&nbsp;10-2</a> outlines some of the most useful matching functions you can use with <code>expect()</code>. For a comprehensive list, consult the Jest documentation for the <a href="https://oreil.ly/hnbiy"><code>expect()</code> method</a>.</p>
        <table id="jest_matchers">
        <caption><span class="label">Table 10-2. </span>Jest matchers</caption>
        <thead>
        <tr>
        <th>Function</th>
        <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td><p><code>arrayContaining()</code></p></td>
        <td><p>Searches an array for a given value.</p></td>
        </tr>
        <tr>
        <td><p><code>not()</code></p></td>
        <td><p>Allows you to reverse any condition. For example, using <code>expect(...).not.toBe(5)`</code> passes if the value is <em>not</em> 5.</p></td>
        </tr>
        <tr>
        <td><p><code>stringContaining()</code></p></td>
        <td><p>Searches a string for a substring.</p></td>
        </tr>
        <tr>
        <td><p><code>stringMatching()</code></p></td>
        <td><p>Attempts to match a string to a regular expression.</p></td>
        </tr>
        <tr>
        <td><p><code>toBe()</code></p></td>
        <td><p>Tests for standard JavaScript equality, just as if you used the <code>==</code> operator.</p></td>
        </tr>
        <tr>
        <td><p><code>toBeCloseTo()</code></p></td>
        <td><p>Tests that two numbers are equal or <em>very</em> close. Intended to avoid minute rounding errors with floating-point numbers (an issue detailed in <a data-type="xref" href="ch03.html#preserving_decimal_accuracy">“Preserving Accuracy in Decimal Values”</a>).</p></td>
        </tr>
        <tr>
        <td><p><code>toBeGreaterThan()</code></p></td>
        <td><p>Checks if a numeric value is greater than the value you specify. There’s a small set of similar matchers for different comparisons, including <code>toBeGreaterThanOrEqual()</code>, <code>toBeLessThan()</code>, and <code>toBeLessThanOrEqual()</code>.</p></td>
        </tr>
        <tr>
        <td><p><code>toBeInstanceOf()</code></p></td>
        <td><p>Checks if a returned object is an instance of a specified class, just as if you used the <code>instanceof</code> operator.</p></td>
        </tr>
        <tr>
        <td><p><code>toBeNull()</code></p></td>
        <td><p>Checks if a value is <code>null</code>. You can also test for <code>NaN</code> values with <code>toBeNaN()</code> and undefined values with <code>toBeUndefined()</code>.</p></td>
        </tr>
        <tr>
        <td><p><code>toBeTruthy()</code></p></td>
        <td><p><a data-type="indexterm" data-primary="truthy values" id="idm45475150781640"></a>Tests if a number is <em>truthy</em>, which means it will be coerced to <code>true</code> in an <code>if</code> statement. In JavaScript, everything is truthy except <code>null</code>, <code>undefined</code>, empty strings, <code>NaN</code>, <code>0</code>, and <code>false</code>.</p></td>
        </tr>
        <tr>
        <td><p><code>toEqual()</code></p></td>
        <td><p>Performs a <em>deep comparison</em> that checks if one object has the same content as another. This is in contrast to <code>toBe()</code>, which tests reference equality for objects. As a general rule of thumb, <code>toBe()</code> works for primitive types, but <code>toEqual()</code> is what you need to compare object instances. (<a data-type="xref" href="ch07.html#deep_clone_an_object">“Making a Deep Copy of an Object”</a> explains more about object equality in JavaScript.)</p></td>
        </tr>
        <tr>
        <td><p><code>toHaveProperty()</code></p></td>
        <td><p>Checks if a returned object has a specific property and (optionally) if that property matches a certain value.</p></td>
        </tr>
        <tr>
        <td><p><code>toStrictEqual()</code></p></td>
        <td><p>Similar to <code>toEqual()</code> but requires the objects to match exactly. For example, objects with the same properties and property values won’t match if they are instances of different classes, or if one is a class instance and the other an object literal.</p></td>
        </tr>
        <tr>
        <td><p><code>toThrow</code></p></td>
        <td><p>Tests if the function throws an exception. You can optionally require the exception to be a specific error object.</p></td>
        </tr>
        </tbody>
        </table>
        
        <p><a data-type="indexterm" data-primary="toThrow() function" id="idm45475150766232"></a>To fix the current example, you can indicate that you expect a value of <code>NaN</code> to throw an exception with the <code>toThrow()</code> matcher. However, <code>toThrow()</code> requires an extra step. You need to wrap the code inside <code>expect()</code> inside <em>another</em> anonymous function. Otherwise, the exception won’t be caught and the test will still fail. Here’s the correct code:</p>
        
        <pre data-type="programlisting" data-code-language="javascript"><code class="nx">test</code><code class="p">(</code><code class="s1">'NaN causes error'</code><code class="p">,</code> <code class="p">()</code> <code class="o">=&gt;</code> <code class="p">{</code>
          <code class="nx">expect</code><code class="p">(()</code> <code class="o">=&gt;</code> <code class="p">{</code>
            <code class="nx">factorialize</code><code class="p">(</code><code class="kc">NaN</code><code class="p">);</code>
          <code class="p">}).</code><code class="nx">toThrow</code><code class="p">();</code>
        <code class="p">});</code></pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="See Also"><div class="sect2" id="idm45475150671800">
        <h2>See Also</h2>
        
        <p>This example gives a good overview of Jest’s core functionality, but there are many additional features you may want to consider. For example, Jest has additional support for using mock data, handling asynchronous results from promises, simulating timers, and snapshot testing (which verifies that the UI of a page hasn’t changed). For more information about all these features, refer to the <a href="https://oreil.ly/aeu1l">Jest documentation</a>.<a data-type="indexterm" data-primary="" data-startref="ix_test_write_unit" id="idm45475150753288"></a><a data-type="indexterm" data-primary="" data-startref="ix_unit_test_write" id="idm45475150752280"></a><a data-type="indexterm" data-primary="" data-startref="ix_jest_test" id="idm45475150751336"></a><a data-type="indexterm" data-primary="" data-startref="ix_functions_jest" id="idm45475150750392"></a></p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Extra: Writing Tests First"><div class="sect2" id="idm45475150749192">
        <h2>Extra: Writing Tests First</h2>
        
        <p><a data-type="indexterm" data-primary="code" data-secondary="programming approaches" id="idm45475150747816"></a><a data-type="indexterm" data-primary="libraries" data-secondary="writing tests first before" id="idm45475150746840"></a><a data-type="indexterm" data-primary="TDD (Test-Driven Development)" id="idm45475150745928"></a>Modern development practices have embraced the idea of writing the tests before much of the functionality for the application (and libraries) is written. <a data-type="indexterm" data-primary="Agile development paradigm" id="idm45475150687304"></a>This test-driven development (TDD) is a component of the Agile development paradigm.</p>
        
        <p><a data-type="indexterm" data-primary="waterfall project design" id="idm45475150686280"></a><a data-type="indexterm" data-primary="structured programming" id="idm45475150685560"></a>TDD takes some getting used to. Rather than a more formal <em>structured programming</em> or <em>waterfall</em> project design, which delays testing until you have reasonably complete code, TDD mandates that you write tests before your write anything else. Here’s how it unfolds:</p>
        <ol>
        <li>
        <p><em>Define the tests.</em> For example, if you were planning to write the <code>factorialize()</code> function shown in the previous example, you would begin by defining a representative set of tests that capture its expected inputs: for example, the largest number it can factorialize, boundary values like 0, and potential edge cases (like an implicitly coerced string or <code>BigInt</code> value). You would also write tests to check that failure cases are treated appropriately—in this case, by throwing the expected error.</p>
        </li>
        <li>
        <p><em>Make it fail.</em> Once you’ve written your tests, you write the code. Some TDD practitioners suggest that the first step is to make your code compile and your tests fail. By achieving this step, you ensure that your tests are running, your test requirements are meaningful, and you aren’t accidentally passing code before it’s complete.</p>
        </li>
        <li>
        <p><em>Make it pass.</em> The next step is sometimes described as “make the tests pass any way possible.” In other words, you don’t worry about creating the best possible solution, but simply making all the tests pass. Do not write more code than dictated by the test requirements.</p>
        </li>
        <li>
        <p><em>Refactor.</em> After you successfully pass your tests, you start the work of refining the code. This is the time when you refactor, remove duplicate code, and introduce improvements, repeating your tests all the while to make sure they continue to pass. You’ll probably also discover cases you haven’t covered, and end up writing more tests.</p>
        </li>
        
        </ol>
        
        <p>One obvious advantage in TDD is that it makes you focus on the problem at hand. You don’t need to interpret design requirements to decide how you should code a solution. Instead, you code to the exacting specifications that are formalized in tests. But TDD development also helps as an application evolves, because it diminishes the fear of change. As long as your code continues to pass the tests you’ve set out, and as long as your tests are truly representative (a bigger “if”), it’s safe to commit new revisions to your codebase.</p>
        
        <p>The cost for this protection is that creating proper tests takes significantly more time to complete and significant experience to get right. One metric that can help you evaluate your testing regimen is <em>test code coverage</em> (<a data-type="xref" href="#unit_testing_coverage">“Tracking Test Code Coverage”</a>).</p>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect1" data-pdf-bookmark="Tracking Test Code Coverage"><div class="sect1" id="unit_testing_coverage">
        <h1>Tracking Test Code Coverage</h1>
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Problem"><div class="sect2" id="idm45475150648200">
        <h2>Problem</h2>
        
        <p><a data-type="indexterm" data-primary="code" data-secondary="test code coverage" id="ix_code_coverage"></a><a data-type="indexterm" data-primary="test code coverage" id="ix_test_code_cover"></a>You want to assess how well your test cases cover all the possibilities in your code.</p>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Solution"><div class="sect2" id="idm45475150644616">
        <h2>Solution</h2>
        
        <p><a data-type="indexterm" data-primary="Jest" id="idm45475150643240"></a>Get a code coverage report from your testing tool. In Jest, you use the <code>--collect-coverage</code> option:</p>
        
        <pre data-type="programlisting">$ npx jest --collect-coverage</pre>
        
        <p>Now Jest will run all the tests in all the <em>test.js</em> files (as usual), followed by a more detailed report that analyzes the code coverage of your tests. Here’s the report with the tests for the <code>factorialize()</code> function shown in <a data-type="xref" href="#unit_testing">“Writing Unit Tests for Your Code”</a>:</p>
        
        <pre data-type="programlisting">-----------------|---------|----------|---------|---------|-------------------
        File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
        -----------------|---------|----------|---------|---------|-------------------
        All files        |   82.61 |    66.67 |     100 |   82.61 |
         factorialize.js |   82.61 |    66.67 |     100 |   82.61 | 3-4,6-7
        -----------------|---------|----------|---------|---------|-------------------
        Test Suites: 1 passed, 1 total
        Tests:       4 passed, 4 total
        Snapshots:   0 total
        Time:        2.741 s</pre>
        </div></section>
        
        
        
        
        
        
        
        
        
        
        
        
        
        <section data-type="sect2" data-pdf-bookmark="Discussion"><div class="sect2" id="idm45475150637592">
        <h2>Discussion</h2>
        
        <p>Determining test code coverage requires a multifaceted approach. To be successful, it should include techniques such as code reviews and walkthroughs with peers. However, all testing tools also include automated code analysis features that can help you size up how successful your tests are at evaluating your code.</p>
        
        <p>In Jest, the <code>--collect-coverage</code> parameter triggers this analysis. You can use this parameter at the command line or add it to the <code>jest</code> command in the <em>package.json</em> configuration file for your application.</p>
        
        <p>The code coverage report assesses how much of your code is tested using several percentages, which appear in separate columns:</p>
        <dl>
        <dt>Functions</dt>
        <dd>
        <p>Shows how many of your functions are tested. This is a good starting point for evaluating your test coverage, but it’s also the least fine-grained statistic. In the <code>factorialize()</code> test, all the functions are tested. That doesn’t mean that all the code in these functions is executed!</p>
        </dd>
        <dt>Statements</dt>
        <dd>
        <p>Shows the percentage of code statements that are executed during your tests. In the <code>factorialize()</code> test, roughly 83% of all the code written is covered by at least one test.</p>
        </dd>
        <dt>Branch</dt>
        <dd>
        <p>Shows how many different branches (through conditional logic, like <code>if</code> statements) are reached. In the <code>factorialize()</code> test, the tests travel down 67% of the separate conditional branches.</p>
        </dd>
        </dl>
        
        <p>Additionally, the code report can point you to lines that don’t have code coverage. For example, the <code>factorialize()</code> example highlights lines 3–4 in your source code file, which rejects negative numbers, and lines 6–7, which rejects noninteger numbers. To improve your test code coverage, you could write a test assertion that uses <code>toThrow()</code> to ensure that both these cases are rejected properly.</p>
        
        <p>The command-line report gives you a quick review of your coverage, but Jest also generates a more comprehensive HTML-formatted report, which it stores in the <em>coverage</em> folder. Open <em>index.html</em> to see a list of all the tested files with the top-line statistics in slightly more detail (see <a data-type="xref" href="#test_report_1">Figure&nbsp;10-1</a>). For example, rather than just giving you percentages, the report tells you the exact number of statements, branches, and functions. Click on any file in the list to go to another page that shows the code, with a twist: uncovered statements are highlighted for quick reference (see <a data-type="xref" href="#test_report_2">Figure&nbsp;10-2</a>).</p>
        
        <figure class="no-frame"><div id="test_report_1" class="figure">
        <img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781492055747/files/assets/jsc3_1001.png" alt="jsc3 1001" width="1445" height="615">
        <h6><span class="label">Figure 10-1. </span>Code coverage report</h6>
        </div></figure>
        
        <figure class="no-frame"><div id="test_report_2" class="figure">
        <img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781492055747/files/assets/jsc3_1002.png" alt="jsc3 1002" width="1445" height="935">
        <h6><span class="label">Figure 10-2. </span>Highlighted code without test coverage</h6>
        </div></figure>
        <div data-type="note" epub:type="note"><h6>Note</h6>
        <p>The appropriate test coverage goal is much-debated. Some developers advocate for getting as close to 100% as possible, while others argue that 70%–80% is more practical and achieves the best return for your test-writing investment. However, the honest answer is that test coverage is not a definitive metric. <a data-type="indexterm" data-primary="" data-startref="ix_testing_ch10" id="idm45475150615480"></a><a data-type="indexterm" data-primary="" data-startref="ix_test_code_cover" id="idm45475150614504"></a><a data-type="indexterm" data-primary="" data-startref="ix_code_coverage" id="idm45475150613560"></a>Not only does the percentage differ based on how you measure it (functions, statements, or branches), but testing tools have no way to identify the riskiest or most vulnerable paths in your codebase.</p>
        </div>
        </div></section>
        
        
        
        
        
        </div></section>
        
        
        
        
        
        
        
        </div></section></div></div><link rel="stylesheet" href="/files/public/epub-reader/override_v1.css" crossorigin="anonymous"><link rel="stylesheet" href="/api/v2/epubs/urn:orm:book:9781492055747/files/epub.css" crossorigin="anonymous"></div></div></section>
</div>

https://learning.oreilly.com