<style>
    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 300;
        src: url(https://static.contineljs.com/fonts/Roboto-Light.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Light.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 400;
        src: url(https://static.contineljs.com/fonts/Roboto-Regular.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Regular.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 500;
        src: url(https://static.contineljs.com/fonts/Roboto-Medium.woff2?v=2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Medium.woff) format("woff");
    }

    @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 700;
        src: url(https://static.contineljs.com/fonts/Roboto-Bold.woff2) format("woff2"),
            url(https://static.contineljs.com/fonts/Roboto-Bold.woff) format("woff");
    }

    * {
        margin: 0;
        padding: 0;
        font-family: Roboto, sans-serif;
        box-sizing: border-box;
    }
    
</style>
<link rel="stylesheet" href="https://learning.oreilly.com/files/public/epub-reader/override_v1.css" crossorigin="anonymous"><link rel="stylesheet" href="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781492092506/files/epub.css" crossorigin="anonymous">
<div style="width: 100%; display: flex; justify-content: center; background-color: black; color: wheat;">
    <section data-testid="contentViewer" class="contentViewer--KzjY1"><div class="annotatable--okKet"><div id="book-content" class=""><div class="readerContainer--bZ89H white--bfCci" style="font-size: 1em; max-width: 70ch;"><div id="sbo-rt-content"><h2 class="h2 noOutline" id="ch08" tabindex="-1"><span epub:type="pagebreak" id="page_129"></span><span class="f1">8</span><br>BUGS AND ERRORS</h2>
        <p class="intro">Flaws in computer programs are usually called <em>bugs</em>. It makes programmers feel good to imagine them as little things that just happen to crawl into our work. In reality, of course, we put them there ourselves.</p>
        <p class="indent">If a program is crystallized thought, you can roughly categorize bugs into those caused by the thoughts being confused and those caused by mistakes introduced while converting a thought to code. The former type is generally harder to diagnose and fix than the latter.</p>
        <h3 class="h3" id="ch08lev1">Language</h3>
        <p class="noindent">Many mistakes could be pointed out to us automatically by the computer, if it knew enough about what we’re trying to do. But here JavaScript’s looseness is a hindrance. Its concept of bindings and properties is vague enough that it will rarely catch typos before actually running the program. And even then, it allows you to do some clearly nonsensical things without complaint, such as computing <span class="literal">true * "monkey"</span>.</p>
        <p class="indent">There are some things that JavaScript does complain about. Writing a program that does not follow the language’s grammar will immediately make the computer complain. Other things, such as calling something that’s not a function or looking up a property on an undefined value, will cause an error to be reported when the program tries to perform the action.</p>
        <p class="indent"><span epub:type="pagebreak" id="page_130"></span>But often, your nonsense computation will merely produce <span class="literal">NaN</span> (not a number) or an undefined value, while the program happily continues, convinced that it’s doing something meaningful. The mistake will manifest itself only later, after the bogus value has traveled through several functions. It might not trigger an error at all but silently cause the program’s output to be wrong. Finding the source of such problems can be difficult.</p>
        <p class="indent">The process of finding mistakes—bugs—in programs is called <em>debugging</em>.</p>
        <h3 class="h3" id="ch08lev2">Strict Mode</h3>
        <p class="noindent">JavaScript can be made a <em>little</em> stricter by enabling <em>strict mode</em>. This is done by putting the string <span class="literal">"use strict"</span> at the top of a file or a function body. Here’s an example:</p>
        <p class="programs">function canYouSpotTheProblem() {<br>&nbsp;&nbsp;"use strict";<br>&nbsp;&nbsp;for (counter = 0; counter &lt; 10; counter++) {<br>&nbsp;&nbsp;&nbsp;&nbsp;console.log("Happy happy");<br>&nbsp;&nbsp;}<br>}<br><br>canYouSpotTheProblem();<br>// → ReferenceError: counter is not defined</p>
        <p class="indent">Normally, when you forget to put <span class="literal">let</span> in front of your binding, as with <span class="literal">counter</span> in the example, JavaScript quietly creates a global binding and uses that. In strict mode, an error is reported instead. This is very helpful. It should be noted, though, that this doesn’t work when the binding in question already exists as a global binding. In that case, the loop will still quietly overwrite the value of the binding.</p>
        <p class="indent">Another change in strict mode is that the <span class="literal">this</span> binding holds the value <span class="literal">undefined</span> in functions that are not called as methods. When making such a call outside of strict mode, <span class="literal">this</span> refers to the global scope object, which is an object whose properties are the global bindings. So if you accidentally call a method or constructor incorrectly in strict mode, JavaScript will produce an error as soon as it tries to read something from <span class="literal">this</span>, rather than happily writing to the global scope.</p>
        <p class="indent">For example, consider the following code, which calls a constructor function without the <span class="literal">new</span> keyword so that its <span class="literal">this</span> will <em>not</em> refer to a newly constructed object:</p>
        <p class="programs">function Person(name) { this.name = name; }<br>let ferdinand = Person("Ferdinand"); // oops<br>console.log(name);<br>// → Ferdinand</p>
        <p class="indent">So the bogus call to <span class="literal">Person</span> succeeded but returned an undefined value and created the global binding <span class="literal">name</span>. In strict mode, the result is different.</p>
        <p class="programs"><span epub:type="pagebreak" id="page_131"></span>"use strict";<br>function Person(name) { this.name = name; }<br>let ferdinand = Person("Ferdinand"); // forgot new<br>// → TypeError: Cannot set property 'name' of undefined</p>
        <p class="indent">We are immediately told that something is wrong. This is helpful. Fortunately, constructors created with the <span class="literal">class</span> notation will always complain if they are called without <span class="literal">new</span>, making this less of a problem even in non-strict mode.</p>
        <p class="indent">Strict mode does a few more things. It disallows giving a function multiple parameters with the same name and removes certain problematic language features entirely (such as the <span class="literal">with</span> statement, which is so wrong it is not further discussed in this book).</p>
        <p class="indent">In short, putting <span class="literal">"use strict"</span> at the top of your program rarely hurts and might help you spot a problem.</p>
        <h3 class="h3" id="ch08lev3">Types</h3>
        <p class="noindent">Some languages want to know the types of all your bindings and expressions before even running a program. They will tell you right away when a type is used in an inconsistent way. JavaScript considers types only when actually running the program, and even there often tries to implicitly convert values to the type it expects, so it’s not much help.</p>
        <p class="indent">Still, types provide a useful framework for talking about programs. A lot of mistakes come from being confused about the kind of value that goes into or comes out of a function. If you have that information written down, you’re less likely to get confused.</p>
        <p class="indent">You could add a comment like the following before the <span class="literal">goalOrientedRobot</span> function from the previous chapter to describe its type:</p>
        <p class="programs">// (VillageState, Array)&nbsp;&nbsp;{direction: string, memory: Array}<br>function goalOrientedRobot(state, memory) {<br>&nbsp;&nbsp;// ...<br>}</p>
        <p class="indent">There are a number of different conventions for annotating JavaScript programs with types.</p>
        <p class="indent">One thing about types is that they need to introduce their own complexity to be able to describe enough code to be useful. What do you think would be the type of the <span class="literal">randomPick</span> function that returns a random element from an array? You’d need to introduce a <em>type variable, T</em>, which can stand in for any type, so that you can give <span class="literal">randomPick</span> a type like <span class="literal">([T])</span> → <span class="literal">T</span> (function from an array of <em>T</em> s to a <em>T</em> ).</p>
        <p class="indent">When the types of a program are known, it’s possible for the computer to <em>check</em> them for you, pointing out mistakes before the program is run. There are several JavaScript dialects that add types to the language and <span epub:type="pagebreak" id="page_132"></span>check them. The most popular one is called TypeScript. If you are interested in adding more rigor to your programs, I recommend you give it a try.</p>
        <p class="indent">In this book, we’ll continue using raw, dangerous, untyped JavaScript code.</p>
        <h3 class="h3" id="ch08lev4">Testing</h3>
        <p class="noindent">If the language is not going to do much to help us find mistakes, we’ll have to find them the hard way: by running the program and seeing whether it does the right thing.</p>
        <p class="indent">Doing this by hand, again and again, is a really bad idea. Not only is it annoying, it also tends to be ineffective since it takes too much time to exhaustively test everything every time you make a change.</p>
        <p class="indent">Computers are good at repetitive tasks, and testing is the ideal repetitive task. Automated testing is the process of writing a program that tests another program. Writing tests is a bit more work than testing manually, but once you’ve done it, you gain a kind of superpower: it takes you only a few seconds to verify that your program still behaves properly in all the situations you wrote tests for. When you break something, you’ll immediately notice, rather than randomly running into it at some later time.</p>
        <p class="indent">Tests usually take the form of little labeled programs that verify some aspect of your code. For example, a set of tests for the (standard, probably already tested by someone else) <span class="literal">toUpperCase</span> method might look like this:</p>
        <p class="programs">function test(label, body) {<br>&nbsp;&nbsp;if (!body()) console.log(`Failed: ${label}`);<br>}<br><br>test("convert Latin text to uppercase", () =&gt; {<br>&nbsp;&nbsp;return "hello".toUpperCase() == "HELLO";<br>});<br>test("convert Greek text to uppercase", () =&gt; {<br>&nbsp;&nbsp;return "".toUpperCase() == "";<br>});<br>test("don't convert case-less characters", () =&gt; {<br>&nbsp;&nbsp;return "&nbsp;&nbsp;&nbsp;&nbsp;".toUpperCase() == "&nbsp;&nbsp;&nbsp;&nbsp;";<br>});</p>
        <p class="indent">Writing tests like this tends to produce rather repetitive, awkward code. Fortunately, there exist pieces of software that help you build and run collections of tests (<em>test suites</em>) by providing a language (in the form of functions and methods) suited to expressing tests and by outputting informative information when a test fails. These are usually called <em>test runners</em>.</p>
        <p class="indent">Some code is easier to test than other code. Generally, the more external objects that the code interacts with, the harder it is to set up the context in which to test it. The style of programming shown in the previous chapter, which uses self-contained persistent values rather than changing objects, tends to be easy to test.</p>
        <h3 class="h3" id="ch08lev5"><span epub:type="pagebreak" id="page_133"></span>Debugging</h3>
        <p class="noindent">Once you notice there is something wrong with your program because it misbehaves or produces errors, the next step is to figure out <em>what</em> the problem is.</p>
        <p class="indent">Sometimes it is obvious. The error message will point at a specific line of your program, and if you look at the error description and that line of code, you can often see the problem.</p>
        <p class="indent">But not always. Sometimes the line that triggered the problem is simply the first place where a flaky value produced elsewhere gets used in an invalid way. If you have been solving the exercises in earlier chapters, you will probably have already experienced such situations.</p>
        <p class="indent">The following example program tries to convert a whole number to a string in a given base (decimal, binary, and so on) by repeatedly picking out the last digit and then dividing the number to get rid of this digit. But the strange output that it currently produces suggests that it has a bug.</p>
        <p class="programs">function numberToString(n, base = 10) {<br>&nbsp;&nbsp;let result = "", sign = "";<br>&nbsp;&nbsp;if (n &lt; 0) {<br>&nbsp;&nbsp;&nbsp;&nbsp;sign = "-";<br>&nbsp;&nbsp;&nbsp;&nbsp;n = -n;<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;do {<br>&nbsp;&nbsp;&nbsp;&nbsp;result = String(n % base) + result;<br>&nbsp;&nbsp;&nbsp;&nbsp;n /= base;<br>&nbsp;&nbsp;} while (n &gt; 0);<br>&nbsp;&nbsp;return sign + result;<br>}<br>console.log(numberToString(13, 10));<br>// → 1.5e-3231.3e-3221.3e-3211.3e-3201.3e-3191.3e-3181.3...</p>
        <p class="indent">Even if you see the problem already, pretend for a moment that you don’t. We know that our program is malfunctioning, and we want to find out why.</p>
        <p class="indent">This is where you must resist the urge to start making random changes to the code to see whether that makes it better. Instead, <em>think</em>. Analyze what is happening and come up with a theory of why it might be happening. Then, make additional observations to test this theory—or, if you don’t yet have a theory, make additional observations to help you come up with one.</p>
        <p class="indent">Putting a few strategic <span class="literal">console.log</span> calls into the program is a good way to get additional information about what the program is doing. In this case, we want <span class="literal">n</span> to take the values <span class="literal">13</span>, <span class="literal">1</span>, and then <span class="literal">0</span>. Let’s write out its value at the start of the loop.</p>
        <p class="programs">13<br>1.3<br>0.13<br>0.013<br>...<br>1.5e-323</p>
        <p class="indent"><span epub:type="pagebreak" id="page_134"></span><em>Right</em>. Dividing 13 by 10 does not produce a whole number. Instead of <span class="literal">n /= base</span>, what we actually want is <span class="literal">n = Math.floor(n / base)</span> so that the number is properly “shifted” to the right.</p>
        <p class="indent">An alternative to using <span class="literal">console.log</span> to peek into the program’s behavior is to use the <em>debugger</em> capabilities of your browser. Browsers come with the ability to set a <em>breakpoint</em> on a specific line of your code. When the execution of the program reaches a line with a breakpoint, it is paused, and you can inspect the values of bindings at that point. I won’t go into details, as debuggers differ from browser to browser, but look in your browser’s developer tools or search the web for more information.</p>
        <p class="indent">Another way to set a breakpoint is to include a <span class="literal">debugger</span> statement (consisting of simply that keyword) in your program. If the developer tools of your browser are active, the program will pause whenever it reaches such a statement.</p>
        <h3 class="h3" id="ch08lev6">Error Propagation</h3>
        <p class="noindent">Not all problems can be prevented by the programmer, unfortunately. If your program communicates with the outside world in any way, it is possible to get malformed input, to become overloaded with work, or to have the network fail.</p>
        <p class="indent">If you’re programming only for yourself, you can afford to just ignore such problems until they occur. But if you build something that is going to be used by anybody else, you usually want the program to do better than just crash. Sometimes the right thing to do is take the bad input in stride and continue running. In other cases, it is better to report to the user what went wrong and then give up. But in either situation, the program has to actively do something in response to the problem.</p>
        <p class="indent">Say you have a function <span class="literal">promptNumber</span> that asks the user for a number and returns it. What should it return if the user inputs “orange?”</p>
        <p class="indent">One option is to make it return a special value. Common choices for such values are <span class="literal">null</span>, <span class="literal">undefined</span>, or <span class="literal">-1</span>.</p>
        <p class="programs">function promptNumber(question) {<br>&nbsp;&nbsp;let result = Number(prompt(question));<br>&nbsp;&nbsp;if (Number.isNaN(result)) return null;<br>&nbsp;&nbsp;else return result;<br>}<br><br>console.log(promptNumber("How many trees do you see?"));</p>
        <p class="indent">Now any code that calls <span class="literal">promptNumber</span> must check whether an actual number was read and, failing that, must somehow recover—maybe by asking <span epub:type="pagebreak" id="page_135"></span>again or by filling in a default value. Or it could again return a special value to <em>its</em> caller to indicate that it failed to do what it was asked.</p>
        <p class="indent">In many situations, mostly when errors are common and the caller should be explicitly taking them into account, returning a special value is a good way to indicate an error. It does, however, have its downsides. First, what if the function can already return every possible kind of value? In such a function, you’ll have to do something like wrap the result in an object to be able to distinguish success from failure.</p>
        <p class="programs">function lastElement(array) {<br>&nbsp;&nbsp;if (array.length == 0) {<br>&nbsp;&nbsp;&nbsp;&nbsp;return {failed: true};<br>&nbsp;&nbsp;} else {<br>&nbsp;&nbsp;&nbsp;&nbsp;return {element: array[array.length - 1]};<br>&nbsp;&nbsp;}<br>}</p>
        <p class="indent">The second issue with returning special values is that it can lead to awkward code. If a piece of code calls <span class="literal">promptNumber</span> 10 times, it has to check 10 times whether <span class="literal">null</span> was returned. And if its response to finding <span class="literal">null</span> is to simply return <span class="literal">null</span> itself, callers of the function will in turn have to check for it, and so on.</p>
        <h3 class="h3" id="ch08lev7">Exceptions</h3>
        <p class="noindent">When a function cannot proceed normally, what we would <em>like</em> to do is just stop what we are doing and immediately jump to a place that knows how to handle the problem. This is what <em>exception handling</em> does.</p>
        <p class="indent">Exceptions are a mechanism that makes it possible for code that runs into a problem to <em>raise</em> (or <em>throw</em>) an exception. An exception can be any value. Raising one somewhat resembles a super-charged return from a function: it jumps out of not just the current function but also its callers, all the way down to the first call that started the current execution. This is called <em>unwinding the stack</em>. You may remember the stack of function calls that was mentioned in “The Call Stack” on <a href="ch03.xhtml#page_46">page 46</a>. An exception zooms down this stack, throwing away all the call contexts it encounters.</p>
        <p class="indent">If exceptions always zoomed right down to the bottom of the stack, they would not be of much use. They’d just provide a novel way to blow up your program. Their power lies in the fact that you can set “obstacles” along the stack to <em>catch</em> the exception as it is zooming down. Once you’ve caught an exception, you can do something with it to address the problem and then continue to run the program.</p>
        <p class="indent">Here’s an example:</p>
        <p class="programs">function promptDirection(question) {<br>&nbsp;&nbsp;let result = prompt(question);<br>&nbsp;&nbsp;if (result.toLowerCase() == "left") return "L";<br>&nbsp;&nbsp;if (result.toLowerCase() == "right") return "R";<br>&nbsp;&nbsp;throw new Error("Invalid direction: " + result);<br>}<br><br>function look() {<br>&nbsp;&nbsp;if (promptDirection("Which way?") == "L") {<br>&nbsp;&nbsp;&nbsp;&nbsp;return "a house";<br>&nbsp;&nbsp;} else {<br>&nbsp;&nbsp;&nbsp;&nbsp;return "two angry bears";<br>&nbsp;&nbsp;}<br>}<br><br>try {<br>&nbsp;&nbsp;console.log("You see", look());<br>} catch (error) {<br>&nbsp;&nbsp;console.log("Something went wrong: " + error);<br>}</p>
        <p class="indent"><span epub:type="pagebreak" id="page_136"></span>The <span class="literal">throw</span> keyword is used to raise an exception. Catching one is done by wrapping a piece of code in a <span class="literal">try</span> block, followed by the keyword <span class="literal">catch</span>. When the code in the <span class="literal">try</span> block causes an exception to be raised, the <span class="literal">catch</span> block is evaluated, with the name in parentheses bound to the exception value. After the <span class="literal">catch</span> block finishes—or if the <span class="literal">try</span> block finishes without problems—the program proceeds beneath the entire <span class="literal">try/catch</span> statement.</p>
        <p class="indent">In this case, we used the <span class="literal">Error</span> constructor to create our exception value. This is a standard JavaScript constructor that creates an object with a <span class="literal">message</span> property. In most JavaScript environments, instances of this constructor also gather information about the call stack that existed when the exception was created, a so-called <em>stack trace</em>. This information is stored in the <span class="literal">stack</span> property and can be helpful when trying to debug a problem: it tells us the function where the problem occurred and which functions made the failing call.</p>
        <p class="indent">Note that the <span class="literal">look</span> function completely ignores the possibility that <span class="literal">promptDirection</span> might go wrong. This is the big advantage of exceptions: error-handling code is necessary only at the point where the error occurs and at the point where it is handled. The functions in between can forget all about it.</p>
        <p class="indent">Well, almost . . .</p>
        <h3 class="h3" id="ch08lev8">Cleaning Up After Exceptions</h3>
        <p class="noindent">The effect of an exception is another kind of control flow. Every action that might cause an exception, which is pretty much every function call and property access, might cause control to suddenly leave your code.</p>
        <p class="indent">This means when code has several side effects, even if its “regular” control flow looks like they’ll always all happen, an exception might prevent some of them from taking place.</p>
        <p class="indent"><span epub:type="pagebreak" id="page_137"></span>Here is some really bad banking code.</p>
        <p class="programs">const accounts = {<br>&nbsp;&nbsp;&nbsp;a: 100,<br>&nbsp;&nbsp;&nbsp;b: 0,<br>&nbsp;&nbsp;&nbsp;c: 20<br>};<br><br>function getAccount() {<br>&nbsp;&nbsp;let accountName = prompt("Enter an account name");<br>&nbsp;&nbsp;if (!accounts.hasOwnProperty(accountName)) {<br>&nbsp;&nbsp;&nbsp;&nbsp;throw new Error(`No such account: ${accountName}`);<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;return accountName;<br>}<br><br>function transfer(from, amount) {<br>&nbsp;&nbsp;if (accounts[from] &lt; amount) return;<br>&nbsp;&nbsp;accounts[from] -= amount;<br>&nbsp;&nbsp;accounts[getAccount()] += amount;<br>}</p>
        <p class="indent">The <span class="literal">transfer</span> function transfers a sum of money from a given account to another, asking for the name of the other account in the process. If given an invalid account name, <span class="literal">getAccount</span> throws an exception.</p>
        <p class="indent">But <span class="literal">transfer</span> <em>first</em> removes the money from the account and <em>then</em> calls <span class="literal">getAccount</span> before it adds it to another account. If it is broken off by an exception at that point, it’ll just make the money disappear.</p>
        <p class="indent">That code could have been written a little more intelligently, for example by calling <span class="literal">getAccount</span> before it starts moving money around. But often problems like this occur in more subtle ways. Even functions that don’t look like they will throw an exception might do so in exceptional circumstances or when they contain a programmer mistake.</p>
        <p class="indent">One way to address this is to use fewer side effects. Again, a programming style that computes new values instead of changing existing data helps. If a piece of code stops running in the middle of creating a new value, no one ever sees the half-finished value, and there is no problem.</p>
        <p class="indent">But that isn’t always practical. So there is another feature that <span class="literal">try</span> statements have. They may be followed by a <span class="literal">finally</span> block either instead of or in addition to a <span class="literal">catch</span> block. A <span class="literal">finally</span> block says “no matter <em>what</em> happens, run this code after trying to run the code in the <span class="literal">try</span> block.”</p>
        <p class="programs">function transfer(from, amount) {<br>&nbsp;&nbsp;if (accounts[from] &lt; amount) return;<br>&nbsp;&nbsp;let progress = 0;<br>&nbsp;&nbsp;try {<br>&nbsp;&nbsp;&nbsp;&nbsp;accounts[from] -= amount;<br>&nbsp;&nbsp;&nbsp;&nbsp;progress = 1;<br>&nbsp;&nbsp;&nbsp;&nbsp;accounts[getAccount()] += amount;<br>&nbsp;&nbsp;&nbsp;&nbsp;progress = 2;<br>&nbsp;&nbsp;} finally {<br>&nbsp;&nbsp;&nbsp;&nbsp;if (progress == 1) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;accounts[from] += amount;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;}<br>}</p>
        <p class="indent"><span epub:type="pagebreak" id="page_138"></span>This version of the function tracks its progress, and if, when leaving, it notices that it was aborted at a point where it had created an inconsistent program state, it repairs the damage it did.</p>
        <p class="indent">Note that even though the <span class="literal">finally</span> code is run when an exception is thrown in the <span class="literal">try</span> block, it does not interfere with the exception. After the <span class="literal">finally</span> block runs, the stack continues unwinding.</p>
        <p class="indent">Writing programs that operate reliably even when exceptions pop up in unexpected places is hard. Many people simply don’t bother, and because exceptions are typically reserved for exceptional circumstances, the problem may occur so rarely that it is never even noticed. Whether that is a good thing or a really bad thing depends on how much damage the software will do when it fails.</p>
        <h3 class="h3" id="ch08lev9">Selective Catching</h3>
        <p class="noindent">When an exception makes it all the way to the bottom of the stack without being caught, it gets handled by the environment. What this means differs between environments. In browsers, a description of the error typically gets written to the JavaScript console (reachable through the browser’s Tools or Developer menu). Node.js, the browserless JavaScript environment we will discuss in <a href="ch20.xhtml#ch20">Chapter 20</a>, is more careful about data corruption. It aborts the whole process when an unhandled exception occurs.</p>
        <p class="indent">For programmer mistakes, just letting the error go through is often the best you can do. An unhandled exception is a reasonable way to signal a broken program, and the JavaScript console will, on modern browsers, provide you with some information about which function calls were on the stack when the problem occurred.</p>
        <p class="indent">For problems that are <em>expected</em> to happen during routine use, crashing with an unhandled exception is a terrible strategy.</p>
        <p class="indent">Invalid uses of the language, such as referencing a nonexistent binding, looking up a property on <span class="literal">null</span>, or calling something that’s not a function, will also result in exceptions being raised. Such exceptions can also be caught.</p>
        <p class="indent">When a <span class="literal">catch</span> body is entered, all we know is that <em>something</em> in our <span class="literal">try</span> body caused an exception. But we don’t know <em>what</em> did or <em>which</em> exception it caused.</p>
        <p class="indent">JavaScript (in a rather glaring omission) doesn’t provide direct support for selectively catching exceptions: either you catch them all or you don’t <span epub:type="pagebreak" id="page_139"></span>catch any. This makes it tempting to <em>assume</em> that the exception you get is the one you were thinking about when you wrote the <span class="literal">catch</span> block.</p>
        <p class="indent">But it might not be. Some other assumption might be violated, or you might have introduced a bug that is causing an exception. Here is an example that <em>attempts</em> to keep on calling <span class="literal">promptDirection</span> until it gets a valid answer:</p>
        <p class="programs">for (;;) {<br>&nbsp;&nbsp;try {<br>&nbsp;&nbsp;&nbsp;&nbsp;let dir = promtDirection("Where?"); // → typo!<br>&nbsp;&nbsp;&nbsp;&nbsp;console.log("You chose ", dir);<br>&nbsp;&nbsp;&nbsp;&nbsp;break;<br>&nbsp;&nbsp;} catch (e) {<br>&nbsp;&nbsp;&nbsp;&nbsp;console.log("Not a valid direction. Try again.");<br>&nbsp;&nbsp;}<br>}</p>
        <p class="indent">The <span class="literal">for (;;)</span> construct is a way to intentionally create a loop that doesn’t terminate on its own. We break out of the loop only when a valid direction is given. <em>But</em> we misspelled <span class="literal">promptDirection</span>, which will result in an “undefined variable” error. Because the <span class="literal">catch</span> block completely ignores its exception value (<span class="literal">e</span>), assuming it knows what the problem is, it wrongly treats the binding error as indicating bad input. Not only does this cause an infinite loop, it “buries” the useful error message about the misspelled binding.</p>
        <p class="indent">As a general rule, don’t blanket-catch exceptions unless it is for the purpose of “routing” them somewhere—for example, over the network to tell another system that our program crashed. And even then, think carefully about how you might be hiding information.</p>
        <p class="indent">So we want to catch a <em>specific</em> kind of exception. We can do this by checking in the <span class="literal">catch</span> block whether the exception we got is the one we are interested in and rethrowing it otherwise. But how do we recognize an exception?</p>
        <p class="indent">We could compare its <span class="literal">message</span> property against the error message we happen to expect. But that’s a shaky way to write code—we’d be using information that’s intended for human consumption (the message) to make a programmatic decision. As soon as someone changes (or translates) the message, the code will stop working.</p>
        <p class="indent">Rather, let’s define a new type of error and use <span class="literal">instanceof</span> to identify it.</p>
        <p class="programs">class InputError extends Error {}<br><br>function promptDirection(question) {<br>&nbsp;&nbsp;let result = prompt(question);<br>&nbsp;&nbsp;if (result.toLowerCase() == "left") return "L";<br>&nbsp;&nbsp;if (result.toLowerCase() == "right") return "R";<br>&nbsp;&nbsp;throw new InputError("Invalid direction: " + result);<br>}</p>
        <p class="indent"><span epub:type="pagebreak" id="page_140"></span>The new error class extends <span class="literal">Error</span>. It doesn’t define its own constructor, which means that it inherits the <span class="literal">Error</span> constructor, which expects a string message as argument. In fact, it doesn’t define anything at all—the class is empty. <span class="literal">InputError</span> objects behave like <span class="literal">Error</span> objects, except that they have a different class by which we can recognize them.</p>
        <p class="indent">Now the loop can catch these more carefully.</p>
        <p class="programs">for (;;) {<br>&nbsp;&nbsp;try {<br>&nbsp;&nbsp;&nbsp;&nbsp;let dir = promptDirection("Where?");<br>&nbsp;&nbsp;&nbsp;&nbsp;console.log("You chose ", dir);<br>&nbsp;&nbsp;&nbsp;&nbsp;break;<br>&nbsp;&nbsp;} catch (e) {<br>&nbsp;&nbsp;&nbsp;&nbsp;if (e instanceof InputError) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log("Not a valid direction. Try again.");<br>&nbsp;&nbsp;&nbsp;&nbsp;} else {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw e;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;}<br>}</p>
        <p class="indent">This will catch only instances of <span class="literal">InputError</span> and let unrelated exceptions through. If you reintroduce the typo, the undefined binding error will be properly reported.</p>
        <h3 class="h3" id="ch08lev10">Assertions</h3>
        <p class="noindent"><em>Assertions</em> are checks inside a program that verify that something is the way it is supposed to be. They are used not to handle situations that can come up in normal operation but to find programmer mistakes.</p>
        <p class="indent">If, for example, <span class="literal">firstElement</span> is described as a function that should never be called on empty arrays, we might write it like this:</p>
        <p class="programs">function firstElement(array) {<br>&nbsp;&nbsp;if (array.length == 0) {<br>&nbsp;&nbsp;&nbsp;&nbsp;throw new Error("firstElement called with []");<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;return array[0];<br>}</p>
        <p class="indent">Now, instead of silently returning undefined (which you get when reading an array property that does not exist), this will loudly blow up your program as soon as you misuse it. This makes it less likely for such mistakes to go unnoticed and easier to find their cause when they occur.</p>
        <p class="indent">I do not recommend trying to write assertions for every possible kind of bad input. That’d be a lot of work and would lead to very noisy code. You’ll <span epub:type="pagebreak" id="page_141"></span>want to reserve them for mistakes that are easy to make (or that you find yourself making).</p>
        <h3 class="h3" id="ch08lev11">Summary</h3>
        <p class="noindent">Mistakes and bad input are facts of life. An important part of programming is finding, diagnosing, and fixing bugs. Problems can become easier to notice if you have an automated test suite or add assertions to your programs.</p>
        <p class="indent">Problems caused by factors outside the program’s control should usually be handled gracefully. Sometimes, when the problem can be handled locally, special return values are a good way to track them. Otherwise, exceptions may be preferable.</p>
        <p class="indent">Throwing an exception causes the call stack to be unwound until the next enclosing <span class="literal">try/catch</span> block or until the bottom of the stack. The exception value will be given to the <span class="literal">catch</span> block that catches it, which should verify that it is actually the expected kind of exception and then do something with it. To help address the unpredictable control flow caused by exceptions, <span class="literal">finally</span> blocks can be used to ensure that a piece of code <em>always</em> runs when a block finishes.</p>
        <h3 class="h3" id="ch08lev12">Exercises</h3>
        <h4 class="h4" id="ch08lev13"><em>Retry</em></h4>
        <p class="noindent">Say you have a function <span class="literal">primitiveMultiply</span> that in 20 percent of cases multiplies two numbers and in the other 80 percent of cases raises an exception of type <span class="literal">MultiplicatorUnitFailure</span>. Write a function that wraps this clunky function and just keeps trying until a call succeeds, after which it returns the result.</p>
        <p class="indent">Make sure you handle only the exceptions you are trying to handle.</p>
        <h4 class="h4" id="ch08lev14"><em>The Locked Box</em></h4>
        <p class="noindent">Consider the following (rather contrived) object:</p>
        <p class="programs">const box = {<br>&nbsp;&nbsp;&nbsp;locked: true,<br>&nbsp;&nbsp;&nbsp;unlock() { this.locked = false; },<br>&nbsp;&nbsp;&nbsp;lock() { this.locked = true; },<br>&nbsp;&nbsp;&nbsp;_content: [],<br>&nbsp;&nbsp;&nbsp;get content() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (this.locked) throw new Error("Locked!");<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return this._content;<br>&nbsp;&nbsp;&nbsp;}<br>};</p>
        <p class="indent"><span epub:type="pagebreak" id="page_142"></span>It is a box with a lock. There is an array in the box, but you can get at it only when the box is unlocked. Directly accessing the private <span class="literal">_content</span> property is forbidden.</p>
        <p class="indent">Write a function called <span class="literal">withBoxUnlocked</span> that takes a function value as argument, unlocks the box, runs the function, and then ensures that the box is locked again before returning, regardless of whether the argument function returned normally or threw an exception.</p>
        <p class="programs">const box = {<br>&nbsp;&nbsp;&nbsp;locked: true,<br>&nbsp;&nbsp;&nbsp;unlock() { this.locked = false; },<br>&nbsp;&nbsp;&nbsp;lock() { this.locked = true; },<br>&nbsp;&nbsp;&nbsp;_content: [],<br>&nbsp;&nbsp;&nbsp;get content() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (this.locked) throw new Error("Locked!");<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return this._content;<br>&nbsp;&nbsp;&nbsp;}<br>};<br><br>function withBoxUnlocked(body) {<br>&nbsp;&nbsp;&nbsp;// Your code here.<br>}<br><br>withBoxUnlocked(function() {<br>&nbsp;&nbsp;&nbsp;box.content.push("gold piece");<br>});<br><br>try {<br>&nbsp;&nbsp;&nbsp;withBoxUnlocked(function() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw new Error("Pirates on the horizon! Abort!");<br>&nbsp;&nbsp;&nbsp;});<br><br>} catch (e) {<br>&nbsp;&nbsp;console.log("Error raised:", e);<br>}<br>console.log(box.locked);<br>// ! true</p>
        <p class="indent">For extra points, make sure that if you call <span class="literal">withBoxUnlocked</span> when the box is already unlocked, the box stays unlocked.<span epub:type="pagebreak" id="page_143"></span></p>
        </div></div><link rel="stylesheet" href="/files/public/epub-reader/override_v1.css" crossorigin="anonymous"><link rel="stylesheet" href="/api/v2/epubs/urn:orm:book:9781492071198/files/styles/9781593279516.css" crossorigin="anonymous"></div></div></section>
</div>

https://learning.oreilly.com